<?php

function ceen_resource_form_complete_edu_standards() {
return array (
  775 => 
  array (
    'name' => 'Colorado Academic Standards',
    'short_name' => 'Colorado',
    'description' => NULL,
    'standard_id' => '775',
    'children' => true,
  ),
  1166 => 
  array (
    'short_name' => '',
    'standard_id' => '1166',
    'name' => 'Science',
    'description' => '',
    'parent_id' => '775',
    'children' => true,
  ),
  776 => 
  array (
    'short_name' => '',
    'standard_id' => '776',
    'name' => 'Standard: 1. Physical Science',
    'description' => '',
    'parent_id' => '1166',
    'children' => true,
  ),
  1171 => 
  array (
    'short_name' => '',
    'standard_id' => '1171',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  779 => 
  array (
    'short_name' => '',
    'standard_id' => '779',
    'name' => 'Newton\'s laws of motion and gravitation describe the relationships among forces acting on and between objects, their masses, and changes in their motion – but have limitations',
    'description' => 'Newton\'s laws of motion and gravitation describe the relationships among forces acting on and between objects, their masses, and changes in their motion – but have limitations',
    'parent_id' => '1171',
    'children' => true,
  ),
  785 => 
  array (
    'short_name' => '',
    'standard_id' => '785',
    'name' => 'Matter has definite structure that determines characteristic physical and chemical properties',
    'description' => 'Matter has definite structure that determines characteristic physical and chemical properties',
    'parent_id' => '1171',
    'children' => true,
  ),
  790 => 
  array (
    'short_name' => '',
    'standard_id' => '790',
    'name' => 'Matter can change form through chemical or nuclear reactions abiding by the laws of conservation of mass and energy',
    'description' => 'Matter can change form through chemical or nuclear reactions abiding by the laws of conservation of mass and energy',
    'parent_id' => '1171',
    'children' => true,
  ),
  795 => 
  array (
    'short_name' => '',
    'standard_id' => '795',
    'name' => 'Atoms bond in different ways to form molecules and compounds that have definite properties',
    'description' => 'Atoms bond in different ways to form molecules and compounds that have definite properties',
    'parent_id' => '1171',
    'children' => true,
  ),
  801 => 
  array (
    'short_name' => '',
    'standard_id' => '801',
    'name' => 'Energy exists in many forms such as mechanical, chemical, electrical, radiant, thermal, and nuclear, that can be quantified and experimentally determined',
    'description' => 'Energy exists in many forms such as mechanical, chemical, electrical, radiant, thermal, and nuclear, that can be quantified and experimentally determined',
    'parent_id' => '1171',
    'children' => true,
  ),
  806 => 
  array (
    'short_name' => '',
    'standard_id' => '806',
    'name' => 'When energy changes form, it is neither created not destroyed; however, because some is necessarily lost as heat, the amount of energy available to do work decreases',
    'description' => 'When energy changes form, it is neither created not destroyed; however, because some is necessarily lost as heat, the amount of energy available to do work decreases',
    'parent_id' => '1171',
    'children' => true,
  ),
  1172 => 
  array (
    'short_name' => '',
    'standard_id' => '1172',
    'name' => '8',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  812 => 
  array (
    'short_name' => '',
    'standard_id' => '812',
    'name' => 'Identify and calculate the direction and magnitude of forces that act on an object, and explain the results in the object\'s change of motion',
    'description' => 'Identify and calculate the direction and magnitude of forces that act on an object, and explain the results in the object\'s change of motion',
    'parent_id' => '1172',
    'children' => true,
  ),
  816 => 
  array (
    'short_name' => '',
    'standard_id' => '816',
    'name' => 'There are different forms of energy, and those forms of energy can be changed from one form to another – but total energy is conserved',
    'description' => 'There are different forms of energy, and those forms of energy can be changed from one form to another – but total energy is conserved',
    'parent_id' => '1172',
    'children' => true,
  ),
  820 => 
  array (
    'short_name' => '',
    'standard_id' => '820',
    'name' => 'Distinguish between physical and chemical changes, noting that mass is conserved during any change',
    'description' => 'Distinguish between physical and chemical changes, noting that mass is conserved during any change',
    'parent_id' => '1172',
    'children' => true,
  ),
  826 => 
  array (
    'short_name' => '',
    'standard_id' => '826',
    'name' => 'Recognize that waves such as electromagnetic, sound, seismic, and water have common characteristics and unique properties',
    'description' => 'Recognize that waves such as electromagnetic, sound, seismic, and water have common characteristics and unique properties',
    'parent_id' => '1172',
    'children' => true,
  ),
  1173 => 
  array (
    'short_name' => '',
    'standard_id' => '1173',
    'name' => '7',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  831 => 
  array (
    'short_name' => '',
    'standard_id' => '831',
    'name' => 'Mixtures of substances can be separated based on their properties such as solubility, boiling points, magnetic properties, and densities',
    'description' => 'Mixtures of substances can be separated based on their properties such as solubility, boiling points, magnetic properties, and densities',
    'parent_id' => '1173',
    'children' => true,
  ),
  1174 => 
  array (
    'short_name' => '',
    'standard_id' => '1174',
    'name' => '6',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  834 => 
  array (
    'short_name' => '',
    'standard_id' => '834',
    'name' => 'All matter is made of atoms, which are far too small to see directly through a light microscope. Elements have unique atoms and thus, unique properties. Atoms themselves are made of even smaller particles',
    'description' => 'All matter is made of atoms, which are far too small to see directly through a light microscope. Elements have unique atoms and thus, unique properties. Atoms themselves are made of even smaller particles',
    'parent_id' => '1174',
    'children' => true,
  ),
  839 => 
  array (
    'short_name' => '',
    'standard_id' => '839',
    'name' => 'Atoms may stick together in well-defined molecules or be packed together in large arrays. Different arrangements of atoms into groups compose all substances',
    'description' => 'Atoms may stick together in well-defined molecules or be packed together in large arrays. Different arrangements of atoms into groups compose all substances',
    'parent_id' => '1174',
    'children' => true,
  ),
  843 => 
  array (
    'short_name' => '',
    'standard_id' => '843',
    'name' => 'The physical characteristics and changes of solid, liquid, and gas states can be explained using the particulate model',
    'description' => 'The physical characteristics and changes of solid, liquid, and gas states can be explained using the particulate model',
    'parent_id' => '1174',
    'children' => true,
  ),
  846 => 
  array (
    'short_name' => '',
    'standard_id' => '846',
    'name' => 'Distinguish among, explain, and apply the relationships among mass, weight, volume, and density',
    'description' => 'Distinguish among, explain, and apply the relationships among mass, weight, volume, and density',
    'parent_id' => '1174',
    'children' => true,
  ),
  1175 => 
  array (
    'short_name' => '',
    'standard_id' => '1175',
    'name' => '5',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  852 => 
  array (
    'short_name' => '',
    'standard_id' => '852',
    'name' => 'Mixtures of matter can be separated regardless of how they were created; all weight and mass of the mixture are the same as the sum of weight and mass of its parts',
    'description' => 'Mixtures of matter can be separated regardless of how they were created; all weight and mass of the mixture are the same as the sum of weight and mass of its parts',
    'parent_id' => '1175',
    'children' => true,
  ),
  1176 => 
  array (
    'short_name' => '',
    'standard_id' => '1176',
    'name' => '4',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  855 => 
  array (
    'short_name' => '',
    'standard_id' => '855',
    'name' => 'Energy comes in many forms such as light, heat, sound, magnetic, chemical, and electrical',
    'description' => 'Energy comes in many forms such as light, heat, sound, magnetic, chemical, and electrical',
    'parent_id' => '1176',
    'children' => true,
  ),
  1177 => 
  array (
    'short_name' => '',
    'standard_id' => '1177',
    'name' => '3',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  860 => 
  array (
    'short_name' => '',
    'standard_id' => '860',
    'name' => 'Matter exists in different states such as solids, liquids, and gases and can change from one state to another by heating and cooling',
    'description' => 'Matter exists in different states such as solids, liquids, and gases and can change from one state to another by heating and cooling',
    'parent_id' => '1177',
    'children' => true,
  ),
  1178 => 
  array (
    'short_name' => '',
    'standard_id' => '1178',
    'name' => '2',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  864 => 
  array (
    'short_name' => '',
    'standard_id' => '864',
    'name' => 'Changes in speed or direction of motion are caused by forces such as pushes and pulls',
    'description' => 'Changes in speed or direction of motion are caused by forces such as pushes and pulls',
    'parent_id' => '1178',
    'children' => true,
  ),
  1179 => 
  array (
    'short_name' => '',
    'standard_id' => '1179',
    'name' => '1',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  867 => 
  array (
    'short_name' => '',
    'standard_id' => '867',
    'name' => 'Solids and liquids have unique properties that distinguish them',
    'description' => 'Solids and liquids have unique properties that distinguish them',
    'parent_id' => '1179',
    'children' => true,
  ),
  1180 => 
  array (
    'short_name' => '',
    'standard_id' => '1180',
    'name' => 'K',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  871 => 
  array (
    'short_name' => '',
    'standard_id' => '871',
    'name' => 'Objects can move in a variety of ways that can be described by speed and direction',
    'description' => 'Objects can move in a variety of ways that can be described by speed and direction',
    'parent_id' => '1180',
    'children' => true,
  ),
  874 => 
  array (
    'short_name' => '',
    'standard_id' => '874',
    'name' => 'Objects can be sorted by physical properties, which can be observed and measured',
    'description' => 'Objects can be sorted by physical properties, which can be observed and measured',
    'parent_id' => '1180',
    'children' => true,
  ),
  1181 => 
  array (
    'short_name' => '',
    'standard_id' => '1181',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '776',
    'children' => true,
  ),
  878 => 
  array (
    'short_name' => '',
    'standard_id' => '878',
    'name' => 'Objects have properties and characteristics',
    'description' => 'Objects have properties and characteristics',
    'parent_id' => '1181',
    'children' => true,
  ),
  882 => 
  array (
    'short_name' => '',
    'standard_id' => '882',
    'name' => 'There are cause-and-effect relationships in everyday experiences',
    'description' => 'There are cause-and-effect relationships in everyday experiences',
    'parent_id' => '1181',
    'children' => true,
  ),
  777 => 
  array (
    'short_name' => '',
    'standard_id' => '777',
    'name' => 'Standard: 2. Life Science',
    'description' => '',
    'parent_id' => '1166',
    'children' => true,
  ),
  1182 => 
  array (
    'short_name' => '',
    'standard_id' => '1182',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  884 => 
  array (
    'short_name' => '',
    'standard_id' => '884',
    'name' => 'Matter tends to be cycled within an ecosystem, while energy is transformed and eventually exits an ecosystem',
    'description' => 'Matter tends to be cycled within an ecosystem, while energy is transformed and eventually exits an ecosystem',
    'parent_id' => '1182',
    'children' => true,
  ),
  893 => 
  array (
    'short_name' => '',
    'standard_id' => '893',
    'name' => 'The size and persistence of populations depend on their interactions with each other and on the abiotic factors in an ecosystem',
    'description' => 'The size and persistence of populations depend on their interactions with each other and on the abiotic factors in an ecosystem',
    'parent_id' => '1182',
    'children' => true,
  ),
  898 => 
  array (
    'short_name' => '',
    'standard_id' => '898',
    'name' => 'Cellular metabolic activities are carried out by biomolecules produced by organisms',
    'description' => 'Cellular metabolic activities are carried out by biomolecules produced by organisms',
    'parent_id' => '1182',
    'children' => true,
  ),
  904 => 
  array (
    'short_name' => '',
    'standard_id' => '904',
    'name' => 'The energy for life primarily derives from the interrelated processes of photosynthesis and cellular respiration. Photosynthesis transforms the sun\'s light energy into the chemical energy of molecular bonds. Cellular respiration allows cells to utilize ch',
    'description' => 'The energy for life primarily derives from the interrelated processes of photosynthesis and cellular respiration. Photosynthesis transforms the sun\'s light energy into the chemical energy of molecular bonds. Cellular respiration allows cells to utilize chemical energy when these bonds are broken.',
    'parent_id' => '1182',
    'children' => true,
  ),
  908 => 
  array (
    'short_name' => '',
    'standard_id' => '908',
    'name' => 'Cells use passive and active transport of substances across membranes to maintain relatively stable intracellular environments',
    'description' => 'Cells use passive and active transport of substances across membranes to maintain relatively stable intracellular environments',
    'parent_id' => '1182',
    'children' => true,
  ),
  914 => 
  array (
    'short_name' => '',
    'standard_id' => '914',
    'name' => 'Cells, tissues, organs, and organ systems maintain relatively stable internal environments, even in the face of changing external environments',
    'description' => 'Cells, tissues, organs, and organ systems maintain relatively stable internal environments, even in the face of changing external environments',
    'parent_id' => '1182',
    'children' => true,
  ),
  919 => 
  array (
    'short_name' => '',
    'standard_id' => '919',
    'name' => 'Physical and behavioral characteristics of an organism are influenced to varying degrees by heritable genes, many of which encode instructions for the production of proteins',
    'description' => 'Physical and behavioral characteristics of an organism are influenced to varying degrees by heritable genes, many of which encode instructions for the production of proteins',
    'parent_id' => '1182',
    'children' => true,
  ),
  925 => 
  array (
    'short_name' => '',
    'standard_id' => '925',
    'name' => 'Multicellularity makes possible a division of labor at the cellular level through the expression of select genes, but not the entire genome.',
    'description' => 'Multicellularity makes possible a division of labor at the cellular level through the expression of select genes, but not the entire genome.',
    'parent_id' => '1182',
    'children' => true,
  ),
  930 => 
  array (
    'short_name' => '',
    'standard_id' => '930',
    'name' => 'Evolution occurs as the heritable characteristics of populations change across generations and can lead populations to become better adapted to their environment',
    'description' => 'Evolution occurs as the heritable characteristics of populations change across generations and can lead populations to become better adapted to their environment',
    'parent_id' => '1182',
    'children' => true,
  ),
  1183 => 
  array (
    'short_name' => '',
    'standard_id' => '1183',
    'name' => '8',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  936 => 
  array (
    'short_name' => '',
    'standard_id' => '936',
    'name' => 'Human activities can deliberately or inadvertently alter ecosystems and their resiliency',
    'description' => 'Human activities can deliberately or inadvertently alter ecosystems and their resiliency',
    'parent_id' => '1183',
    'children' => true,
  ),
  942 => 
  array (
    'short_name' => '',
    'standard_id' => '942',
    'name' => 'Organisms reproduce and transmit genetic information (genes) to offspring, which influences individuals\' traits in the next generation',
    'description' => 'Organisms reproduce and transmit genetic information (genes) to offspring, which influences individuals\' traits in the next generation',
    'parent_id' => '1183',
    'children' => true,
  ),
  1184 => 
  array (
    'short_name' => '',
    'standard_id' => '1184',
    'name' => '7',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  948 => 
  array (
    'short_name' => '',
    'standard_id' => '948',
    'name' => 'Individual organisms with certain traits are more likely than others to survive and have offspring in a specific environment',
    'description' => 'Individual organisms with certain traits are more likely than others to survive and have offspring in a specific environment',
    'parent_id' => '1184',
    'children' => true,
  ),
  953 => 
  array (
    'short_name' => '',
    'standard_id' => '953',
    'name' => 'The human body is composed of atoms, molecules, cells, tissues, organs, and organ systems that have specific functions and interactions',
    'description' => 'The human body is composed of atoms, molecules, cells, tissues, organs, and organ systems that have specific functions and interactions',
    'parent_id' => '1184',
    'children' => true,
  ),
  957 => 
  array (
    'short_name' => '',
    'standard_id' => '957',
    'name' => 'Cells are the smallest unit of life that can function independently and perform all the necessary functions of life',
    'description' => 'Cells are the smallest unit of life that can function independently and perform all the necessary functions of life',
    'parent_id' => '1184',
    'children' => true,
  ),
  962 => 
  array (
    'short_name' => '',
    'standard_id' => '962',
    'name' => 'Photosynthesis and cellular respiration are important processes by which energy is acquired and utilized by organisms',
    'description' => 'Photosynthesis and cellular respiration are important processes by which energy is acquired and utilized by organisms',
    'parent_id' => '1184',
    'children' => true,
  ),
  966 => 
  array (
    'short_name' => '',
    'standard_id' => '966',
    'name' => 'Multiple lines of evidence show the evolution of organisms over geologic time',
    'description' => 'Multiple lines of evidence show the evolution of organisms over geologic time',
    'parent_id' => '1184',
    'children' => true,
  ),
  1185 => 
  array (
    'short_name' => '',
    'standard_id' => '1185',
    'name' => '6',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  971 => 
  array (
    'short_name' => '',
    'standard_id' => '971',
    'name' => 'Changes in environmental conditions can affect the survival of individual organisms, populations, and entire species',
    'description' => 'Changes in environmental conditions can affect the survival of individual organisms, populations, and entire species',
    'parent_id' => '1185',
    'children' => true,
  ),
  976 => 
  array (
    'short_name' => '',
    'standard_id' => '976',
    'name' => 'Organisms interact with each other and their environment in various ways that create a flow of energy and cycling of matter in an ecosystem',
    'description' => 'Organisms interact with each other and their environment in various ways that create a flow of energy and cycling of matter in an ecosystem',
    'parent_id' => '1185',
    'children' => true,
  ),
  1186 => 
  array (
    'short_name' => '',
    'standard_id' => '1186',
    'name' => '5',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  980 => 
  array (
    'short_name' => '',
    'standard_id' => '980',
    'name' => 'All organisms have structures and systems with separate functions',
    'description' => 'All organisms have structures and systems with separate functions',
    'parent_id' => '1186',
    'children' => true,
  ),
  984 => 
  array (
    'short_name' => '',
    'standard_id' => '984',
    'name' => 'Human body systems have basic structures, functions, and needs',
    'description' => 'Human body systems have basic structures, functions, and needs',
    'parent_id' => '1186',
    'children' => true,
  ),
  1187 => 
  array (
    'short_name' => '',
    'standard_id' => '1187',
    'name' => '4',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  990 => 
  array (
    'short_name' => '',
    'standard_id' => '990',
    'name' => 'All living things share similar characteristics, but they also have differences that can be described and classified',
    'description' => 'All living things share similar characteristics, but they also have differences that can be described and classified',
    'parent_id' => '1187',
    'children' => true,
  ),
  995 => 
  array (
    'short_name' => '',
    'standard_id' => '995',
    'name' => 'Comparing fossils to each other or to living organisms reveals features of prehistoric environments and provides information about organisms today',
    'description' => 'Comparing fossils to each other or to living organisms reveals features of prehistoric environments and provides information about organisms today',
    'parent_id' => '1187',
    'children' => true,
  ),
  1002 => 
  array (
    'short_name' => '',
    'standard_id' => '1002',
    'name' => 'There is interaction and interdependence between and among living and nonliving components of ecosystems',
    'description' => 'There is interaction and interdependence between and among living and nonliving components of ecosystems',
    'parent_id' => '1187',
    'children' => true,
  ),
  1188 => 
  array (
    'short_name' => '',
    'standard_id' => '1188',
    'name' => '3',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  1009 => 
  array (
    'short_name' => '',
    'standard_id' => '1009',
    'name' => 'The duration and timing of life cycle events such as reproduction and longevity vary across organisms and species',
    'description' => 'The duration and timing of life cycle events such as reproduction and longevity vary across organisms and species',
    'parent_id' => '1188',
    'children' => true,
  ),
  1189 => 
  array (
    'short_name' => '',
    'standard_id' => '1189',
    'name' => '2',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  1013 => 
  array (
    'short_name' => '',
    'standard_id' => '1013',
    'name' => 'Organisms depend on their habitat\'s nonliving parts to satisfy their needs',
    'description' => 'Organisms depend on their habitat\'s nonliving parts to satisfy their needs',
    'parent_id' => '1189',
    'children' => true,
  ),
  1018 => 
  array (
    'short_name' => '',
    'standard_id' => '1018',
    'name' => 'Each plant or animal has different structures or behaviors that serve different functions',
    'description' => 'Each plant or animal has different structures or behaviors that serve different functions',
    'parent_id' => '1189',
    'children' => true,
  ),
  1190 => 
  array (
    'short_name' => '',
    'standard_id' => '1190',
    'name' => '1',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  1021 => 
  array (
    'short_name' => '',
    'standard_id' => '1021',
    'name' => 'Offspring have characteristics that are similar to but not exactly like their parents\' characteristics',
    'description' => 'Offspring have characteristics that are similar to but not exactly like their parents\' characteristics',
    'parent_id' => '1190',
    'children' => true,
  ),
  1026 => 
  array (
    'short_name' => '',
    'standard_id' => '1026',
    'name' => 'An organism is a living thing that has physical characteristics to help it survive',
    'description' => 'An organism is a living thing that has physical characteristics to help it survive',
    'parent_id' => '1190',
    'children' => true,
  ),
  1191 => 
  array (
    'short_name' => '',
    'standard_id' => '1191',
    'name' => 'K',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  1030 => 
  array (
    'short_name' => '',
    'standard_id' => '1030',
    'name' => 'Organisms can be described and sorted by their physical characteristics',
    'description' => 'Organisms can be described and sorted by their physical characteristics',
    'parent_id' => '1191',
    'children' => true,
  ),
  1192 => 
  array (
    'short_name' => '',
    'standard_id' => '1192',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '777',
    'children' => true,
  ),
  1033 => 
  array (
    'short_name' => '',
    'standard_id' => '1033',
    'name' => 'Living things have characteristics and basic needs',
    'description' => 'Living things have characteristics and basic needs',
    'parent_id' => '1192',
    'children' => true,
  ),
  1038 => 
  array (
    'short_name' => '',
    'standard_id' => '1038',
    'name' => 'Living things develop in predictable patterns',
    'description' => 'Living things develop in predictable patterns',
    'parent_id' => '1192',
    'children' => true,
  ),
  778 => 
  array (
    'short_name' => '',
    'standard_id' => '778',
    'name' => 'Standard: 3. Earth Systems Science',
    'description' => '',
    'parent_id' => '1166',
    'children' => true,
  ),
  1193 => 
  array (
    'short_name' => '',
    'standard_id' => '1193',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1048 => 
  array (
    'short_name' => '',
    'standard_id' => '1048',
    'name' => 'As part of the solar system, Earth interacts with various extraterrestrial forces and energies such as gravity, solar phenomena, electromagnetic radiation, and impact events that influence the planet\'s geosphere, atmosphere, and biosphere in a variety of ',
    'description' => 'As part of the solar system, Earth interacts with various extraterrestrial forces and energies such as gravity, solar phenomena, electromagnetic radiation, and impact events that influence the planet\'s geosphere, atmosphere, and biosphere in a variety of ways',
    'parent_id' => '1193',
    'children' => true,
  ),
  1042 => 
  array (
    'short_name' => '',
    'standard_id' => '1042',
    'name' => 'The history of the universe, solar system and Earth can be inferred from evidence left from past events',
    'description' => 'The history of the universe, solar system and Earth can be inferred from evidence left from past events',
    'parent_id' => '1193',
    'children' => true,
  ),
  1053 => 
  array (
    'short_name' => '',
    'standard_id' => '1053',
    'name' => 'The theory of plate tectonics helps explain geological, physical, and geographical features of Earth',
    'description' => 'The theory of plate tectonics helps explain geological, physical, and geographical features of Earth',
    'parent_id' => '1193',
    'children' => true,
  ),
  1058 => 
  array (
    'short_name' => '',
    'standard_id' => '1058',
    'name' => 'Climate is the result of energy transfer among interactions of the atmosphere, hydrosphere, geosphere, and biosphere',
    'description' => 'Climate is the result of energy transfer among interactions of the atmosphere, hydrosphere, geosphere, and biosphere',
    'parent_id' => '1193',
    'children' => true,
  ),
  1065 => 
  array (
    'short_name' => '',
    'standard_id' => '1065',
    'name' => 'There are costs, benefits, and consequences of exploration, development, and consumption of renewable and nonrenewable resources',
    'description' => 'There are costs, benefits, and consequences of exploration, development, and consumption of renewable and nonrenewable resources',
    'parent_id' => '1193',
    'children' => true,
  ),
  1070 => 
  array (
    'short_name' => '',
    'standard_id' => '1070',
    'name' => 'The interaction of Earth\'s surface with water, air, gravity, and biological activity causes physical and chemical changes',
    'description' => 'The interaction of Earth\'s surface with water, air, gravity, and biological activity causes physical and chemical changes',
    'parent_id' => '1193',
    'children' => true,
  ),
  1075 => 
  array (
    'short_name' => '',
    'standard_id' => '1075',
    'name' => 'Natural hazards have local, national and global impacts such as volcanoes, earthquakes, tsunamis, hurricanes, and thunderstorms',
    'description' => 'Natural hazards have local, national and global impacts such as volcanoes, earthquakes, tsunamis, hurricanes, and thunderstorms',
    'parent_id' => '1193',
    'children' => true,
  ),
  1194 => 
  array (
    'short_name' => '',
    'standard_id' => '1194',
    'name' => '8',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1079 => 
  array (
    'short_name' => '',
    'standard_id' => '1079',
    'name' => 'Weather is a result of complex interactions of Earth\'s atmosphere, land and water, that are driven by energy from the sun, and can be predicted and described through complex models',
    'description' => 'Weather is a result of complex interactions of Earth\'s atmosphere, land and water, that are driven by energy from the sun, and can be predicted and described through complex models',
    'parent_id' => '1194',
    'children' => true,
  ),
  1083 => 
  array (
    'short_name' => '',
    'standard_id' => '1083',
    'name' => 'Earth has a variety of climates defined by average temperature, precipitation, humidity, air pressure, and wind that have changed over time in a particular location',
    'description' => 'Earth has a variety of climates defined by average temperature, precipitation, humidity, air pressure, and wind that have changed over time in a particular location',
    'parent_id' => '1194',
    'children' => true,
  ),
  1087 => 
  array (
    'short_name' => '',
    'standard_id' => '1087',
    'name' => 'The solar system is comprised of various objects that orbit the Sun and are classified based on their characteristics',
    'description' => 'The solar system is comprised of various objects that orbit the Sun and are classified based on their characteristics',
    'parent_id' => '1194',
    'children' => true,
  ),
  1094 => 
  array (
    'short_name' => '',
    'standard_id' => '1094',
    'name' => 'The relative positions and motions of Earth, Moon, and Sun can be used to explain observable effects such as seasons, eclipses, and Moon phases',
    'description' => 'The relative positions and motions of Earth, Moon, and Sun can be used to explain observable effects such as seasons, eclipses, and Moon phases',
    'parent_id' => '1194',
    'children' => true,
  ),
  1195 => 
  array (
    'short_name' => '',
    'standard_id' => '1195',
    'name' => '7',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1098 => 
  array (
    'short_name' => '',
    'standard_id' => '1098',
    'name' => 'Major geologic events such as earthquakes, volcanic eruptions, mid-ocean ridges, and mountain formation are associated with plate boundaries and attributed to plate motions',
    'description' => 'Major geologic events such as earthquakes, volcanic eruptions, mid-ocean ridges, and mountain formation are associated with plate boundaries and attributed to plate motions',
    'parent_id' => '1195',
    'children' => true,
  ),
  1103 => 
  array (
    'short_name' => '',
    'standard_id' => '1103',
    'name' => 'Geologic time, history, and changing life forms are indicated by fossils and successive sedimentation, folding, faulting, and uplifting of layers of sedimentary rock',
    'description' => 'Geologic time, history, and changing life forms are indicated by fossils and successive sedimentation, folding, faulting, and uplifting of layers of sedimentary rock',
    'parent_id' => '1195',
    'children' => true,
  ),
  1196 => 
  array (
    'short_name' => '',
    'standard_id' => '1196',
    'name' => '6',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1108 => 
  array (
    'short_name' => '',
    'standard_id' => '1108',
    'name' => 'Complex interrelationships exist between Earth\'s structure and natural processes that over time are both constructive and destructive',
    'description' => 'Complex interrelationships exist between Earth\'s structure and natural processes that over time are both constructive and destructive',
    'parent_id' => '1196',
    'children' => true,
  ),
  1112 => 
  array (
    'short_name' => '',
    'standard_id' => '1112',
    'name' => 'Water on Earth is distributed and circulated through oceans, glaciers, rivers, ground water, and the atmosphere',
    'description' => 'Water on Earth is distributed and circulated through oceans, glaciers, rivers, ground water, and the atmosphere',
    'parent_id' => '1196',
    'children' => true,
  ),
  1118 => 
  array (
    'short_name' => '',
    'standard_id' => '1118',
    'name' => 'Earth\'s natural resources provide the foundation for human society\'s physical needs. Many natural resources are nonrenewable on human timescales, while others can be renewed or recycled',
    'description' => 'Earth\'s natural resources provide the foundation for human society\'s physical needs. Many natural resources are nonrenewable on human timescales, while others can be renewed or recycled',
    'parent_id' => '1196',
    'children' => true,
  ),
  1197 => 
  array (
    'short_name' => '',
    'standard_id' => '1197',
    'name' => '5',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1123 => 
  array (
    'short_name' => '',
    'standard_id' => '1123',
    'name' => 'Earth and Sun provide a diversity of renewable and nonrenewable resources',
    'description' => 'Earth and Sun provide a diversity of renewable and nonrenewable resources',
    'parent_id' => '1197',
    'children' => true,
  ),
  1126 => 
  array (
    'short_name' => '',
    'standard_id' => '1126',
    'name' => 'Earth\'s surface changes constantly through a variety of processes and forces',
    'description' => 'Earth\'s surface changes constantly through a variety of processes and forces',
    'parent_id' => '1197',
    'children' => true,
  ),
  1129 => 
  array (
    'short_name' => '',
    'standard_id' => '1129',
    'name' => 'Weather conditions change because of the uneven heating of Earth\'s surface by the Sun\'s energy. Weather changes are measured by differences in temperature, air pressure, wind and water in the atmosphere and type of precipitation',
    'description' => 'Weather conditions change because of the uneven heating of Earth\'s surface by the Sun\'s energy. Weather changes are measured by differences in temperature, air pressure, wind and water in the atmosphere and type of precipitation',
    'parent_id' => '1197',
    'children' => true,
  ),
  1198 => 
  array (
    'short_name' => '',
    'standard_id' => '1198',
    'name' => '4',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1134 => 
  array (
    'short_name' => '',
    'standard_id' => '1134',
    'name' => 'Earth is part of the solar system, which includes the Sun, Moon, and other bodies that orbit the Sun in predictable patterns that lead to observable paths of objects in the sky as seen from Earth',
    'description' => 'Earth is part of the solar system, which includes the Sun, Moon, and other bodies that orbit the Sun in predictable patterns that lead to observable paths of objects in the sky as seen from Earth',
    'parent_id' => '1198',
    'children' => true,
  ),
  1199 => 
  array (
    'short_name' => '',
    'standard_id' => '1199',
    'name' => '3',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1139 => 
  array (
    'short_name' => '',
    'standard_id' => '1139',
    'name' => 'Earth\'s materials can be broken down and/or combined into different materials such as rocks, minerals, rock cycle, formation of soil, and sand – some of which are usable resources for human activity',
    'description' => 'Earth\'s materials can be broken down and/or combined into different materials such as rocks, minerals, rock cycle, formation of soil, and sand – some of which are usable resources for human activity',
    'parent_id' => '1199',
    'children' => true,
  ),
  1200 => 
  array (
    'short_name' => '',
    'standard_id' => '1200',
    'name' => '2',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1143 => 
  array (
    'short_name' => '',
    'standard_id' => '1143',
    'name' => 'Weather and the changing seasons impact the environment and organisms such as humans, plants, and other animals',
    'description' => 'Weather and the changing seasons impact the environment and organisms such as humans, plants, and other animals',
    'parent_id' => '1200',
    'children' => true,
  ),
  1201 => 
  array (
    'short_name' => '',
    'standard_id' => '1201',
    'name' => '1',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1147 => 
  array (
    'short_name' => '',
    'standard_id' => '1147',
    'name' => 'Earth\'s materials can be compared and classified based on their properties',
    'description' => 'Earth\'s materials can be compared and classified based on their properties',
    'parent_id' => '1201',
    'children' => true,
  ),
  1202 => 
  array (
    'short_name' => '',
    'standard_id' => '1202',
    'name' => 'K',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1154 => 
  array (
    'short_name' => '',
    'standard_id' => '1154',
    'name' => 'The Sun provides heat and light to Earth',
    'description' => 'The Sun provides heat and light to Earth',
    'parent_id' => '1202',
    'children' => true,
  ),
  1203 => 
  array (
    'short_name' => '',
    'standard_id' => '1203',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '778',
    'children' => true,
  ),
  1159 => 
  array (
    'short_name' => '',
    'standard_id' => '1159',
    'name' => 'Earth\'s materials have properties and characteristics that affect how we use those materials',
    'description' => 'Earth\'s materials have properties and characteristics that affect how we use those materials',
    'parent_id' => '1203',
    'children' => true,
  ),
  1163 => 
  array (
    'short_name' => '',
    'standard_id' => '1163',
    'name' => 'Events such as night, day, the movement of objects in the sky, weather, and seasons have patterns',
    'description' => 'Events such as night, day, the movement of objects in the sky, weather, and seasons have patterns',
    'parent_id' => '1203',
    'children' => true,
  ),
  1633 => 
  array (
    'short_name' => '',
    'standard_id' => '1633',
    'name' => 'English',
    'description' => '',
    'parent_id' => '775',
    'children' => true,
  ),
  1635 => 
  array (
    'short_name' => '',
    'standard_id' => '1635',
    'name' => 'Standard: 1. Oral Expression and Listening',
    'description' => '',
    'parent_id' => '1633',
    'children' => true,
  ),
  1637 => 
  array (
    'short_name' => '',
    'standard_id' => '1637',
    'name' => '12',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1644 => 
  array (
    'short_name' => '',
    'standard_id' => '1644',
    'name' => 'Effective speaking in formal and informal settings requires appropriate use of methods and audience awareness',
    'description' => 'Effective speaking in formal and informal settings requires appropriate use of methods and audience awareness',
    'parent_id' => '1637',
    'children' => true,
  ),
  1654 => 
  array (
    'short_name' => '',
    'standard_id' => '1654',
    'name' => 'Effective collaborative groups accomplish goals',
    'description' => 'Effective collaborative groups accomplish goals',
    'parent_id' => '1637',
    'children' => true,
  ),
  1694 => 
  array (
    'short_name' => '',
    'standard_id' => '1694',
    'name' => '11',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1696 => 
  array (
    'short_name' => '',
    'standard_id' => '1696',
    'name' => 'Verbal and nonverbal cues impact the intent of communication',
    'description' => '',
    'parent_id' => '1694',
    'children' => true,
  ),
  1708 => 
  array (
    'short_name' => '',
    'standard_id' => '1708',
    'name' => 'Validity of a message is determined by its accuracy and relevance',
    'description' => 'Validity of a message is determined by its accuracy and relevance',
    'parent_id' => '1694',
    'children' => true,
  ),
  1721 => 
  array (
    'short_name' => '',
    'standard_id' => '1721',
    'name' => '10',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1722 => 
  array (
    'short_name' => '',
    'standard_id' => '1722',
    'name' => 'Content that is gathered carefully and organized well successfully influences an audience',
    'description' => '',
    'parent_id' => '1721',
    'children' => true,
  ),
  1741 => 
  array (
    'short_name' => '',
    'standard_id' => '1741',
    'name' => 'Effectively operating in small and large groups to accomplish a goal requires active listening',
    'description' => '',
    'parent_id' => '1721',
    'children' => true,
  ),
  1751 => 
  array (
    'short_name' => '',
    'standard_id' => '1751',
    'name' => '9',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1752 => 
  array (
    'short_name' => '',
    'standard_id' => '1752',
    'name' => 'Oral presentations require effective preparation strategies',
    'description' => '',
    'parent_id' => '1751',
    'children' => true,
  ),
  1764 => 
  array (
    'short_name' => '',
    'standard_id' => '1764',
    'name' => 'Listening critically to comprehend a speaker\'s message requires mental and physical strategies to direct and maintain attention',
    'description' => '',
    'parent_id' => '1751',
    'children' => true,
  ),
  1774 => 
  array (
    'short_name' => '',
    'standard_id' => '1774',
    'name' => '8',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1775 => 
  array (
    'short_name' => '',
    'standard_id' => '1775',
    'name' => 'Communication skills and interviewing techniques are required to gather information and to develop and deliver oral presentations',
    'description' => '',
    'parent_id' => '1774',
    'children' => true,
  ),
  1784 => 
  array (
    'short_name' => '',
    'standard_id' => '1784',
    'name' => 'A variety of response strategies clarifies meaning or messages',
    'description' => '',
    'parent_id' => '1774',
    'children' => true,
  ),
  1794 => 
  array (
    'short_name' => '',
    'standard_id' => '1794',
    'name' => '7',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1795 => 
  array (
    'short_name' => '',
    'standard_id' => '1795',
    'name' => 'Formal presentations require preparation and effective delivery',
    'description' => '',
    'parent_id' => '1794',
    'children' => true,
  ),
  1806 => 
  array (
    'short_name' => '',
    'standard_id' => '1806',
    'name' => 'Small and large group discussions rely on active listening and the effective contributions of all participants',
    'description' => '',
    'parent_id' => '1794',
    'children' => true,
  ),
  1832 => 
  array (
    'short_name' => '',
    'standard_id' => '1832',
    'name' => '6',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1833 => 
  array (
    'short_name' => '',
    'standard_id' => '1833',
    'name' => 'Successful group discussions require planning and participation by all',
    'description' => '',
    'parent_id' => '1832',
    'children' => true,
  ),
  1841 => 
  array (
    'short_name' => '',
    'standard_id' => '1841',
    'name' => '5',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1852 => 
  array (
    'short_name' => '',
    'standard_id' => '1852',
    'name' => 'Listening strategies are techniques that contribute to understanding different situations and serving different purposes',
    'description' => '',
    'parent_id' => '1841',
    'children' => true,
  ),
  1842 => 
  array (
    'short_name' => '',
    'standard_id' => '1842',
    'name' => 'Effective communication requires speakers to express an opinion, provide information, describe a process, and persuade an audience',
    'description' => '',
    'parent_id' => '1841',
    'children' => true,
  ),
  1879 => 
  array (
    'short_name' => '',
    'standard_id' => '1879',
    'name' => '4',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1882 => 
  array (
    'short_name' => '',
    'standard_id' => '1882',
    'name' => 'A clear communication plan is necessary to effectively deliver and receive information',
    'description' => '',
    'parent_id' => '1879',
    'children' => true,
  ),
  1892 => 
  array (
    'short_name' => '',
    'standard_id' => '1892',
    'name' => '3',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1896 => 
  array (
    'short_name' => '',
    'standard_id' => '1896',
    'name' => 'Successful group activities need the cooperation of everyone',
    'description' => '',
    'parent_id' => '1892',
    'children' => true,
  ),
  1911 => 
  array (
    'short_name' => '',
    'standard_id' => '1911',
    'name' => 'Oral communication is used both informally and formally',
    'description' => '',
    'parent_id' => '1892',
    'children' => true,
  ),
  1928 => 
  array (
    'short_name' => '',
    'standard_id' => '1928',
    'name' => '2',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1934 => 
  array (
    'short_name' => '',
    'standard_id' => '1934',
    'name' => 'Discussions contribute and expand on the ideas of self and others',
    'description' => '',
    'parent_id' => '1928',
    'children' => true,
  ),
  1952 => 
  array (
    'short_name' => '',
    'standard_id' => '1952',
    'name' => 'New information can be learned and better dialogue created by listening actively',
    'description' => '',
    'parent_id' => '1928',
    'children' => true,
  ),
  1965 => 
  array (
    'short_name' => '',
    'standard_id' => '1965',
    'name' => '1',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  1975 => 
  array (
    'short_name' => '',
    'standard_id' => '1975',
    'name' => 'Multiple strategies develop and expand oral vocabulary',
    'description' => '',
    'parent_id' => '1965',
    'children' => true,
  ),
  1985 => 
  array (
    'short_name' => '',
    'standard_id' => '1985',
    'name' => 'Identifying and manipulating phonemes in spoken words allow people to understand the meaning of speech',
    'description' => '',
    'parent_id' => '1965',
    'children' => true,
  ),
  1997 => 
  array (
    'short_name' => '',
    'standard_id' => '1997',
    'name' => 'Verbal and nonverbal language is used to express and receive information',
    'description' => '',
    'parent_id' => '1965',
    'children' => true,
  ),
  2014 => 
  array (
    'short_name' => '',
    'standard_id' => '2014',
    'name' => 'K',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  2017 => 
  array (
    'short_name' => '',
    'standard_id' => '2017',
    'name' => 'Oral communication skills are built within a language-rich environment',
    'description' => '',
    'parent_id' => '2014',
    'children' => true,
  ),
  2034 => 
  array (
    'short_name' => '',
    'standard_id' => '2034',
    'name' => 'Vocal sounds produce words and meaning to create early knowledge of phonemic awareness',
    'description' => '',
    'parent_id' => '2014',
    'children' => true,
  ),
  2060 => 
  array (
    'short_name' => '',
    'standard_id' => '2060',
    'name' => 'Communication relies on effective verbal and nonverbal skills',
    'description' => '',
    'parent_id' => '2014',
    'children' => true,
  ),
  2079 => 
  array (
    'short_name' => '',
    'standard_id' => '2079',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '1635',
    'children' => true,
  ),
  2083 => 
  array (
    'short_name' => '',
    'standard_id' => '2083',
    'name' => 'Conceptual understanding conveyed through vocabulary words can occur using a variety of modalities',
    'description' => '',
    'parent_id' => '2079',
    'children' => true,
  ),
  2096 => 
  array (
    'short_name' => '',
    'standard_id' => '2096',
    'name' => 'Listening and comprehension skills are required to be clearly understood',
    'description' => '',
    'parent_id' => '2079',
    'children' => true,
  ),
  2108 => 
  array (
    'short_name' => '',
    'standard_id' => '2108',
    'name' => 'Early knowledge of phonemic awareness is the building block of understanding language',
    'description' => '',
    'parent_id' => '2079',
    'children' => true,
  ),
  2146 => 
  array (
    'short_name' => '',
    'standard_id' => '2146',
    'name' => 'Standard: 2. Reading for All Purposes',
    'description' => '',
    'parent_id' => '1633',
    'children' => true,
  ),
  2148 => 
  array (
    'short_name' => '',
    'standard_id' => '2148',
    'name' => '12',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2149 => 
  array (
    'short_name' => '',
    'standard_id' => '2149',
    'name' => 'Literary criticism of complex texts requires the use of analysis, interpretive, and evaluative strategies',
    'description' => '',
    'parent_id' => '2148',
    'children' => true,
  ),
  2163 => 
  array (
    'short_name' => '',
    'standard_id' => '2163',
    'name' => 'Interpreting and evaluating complex informational texts require the understanding of rhetoric, critical reading, and analysis skills',
    'description' => '',
    'parent_id' => '2148',
    'children' => true,
  ),
  2170 => 
  array (
    'short_name' => '',
    'standard_id' => '2170',
    'name' => '11',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2171 => 
  array (
    'short_name' => '',
    'standard_id' => '2171',
    'name' => 'Complex literary texts require critical reading approaches to effectively interpret and evaluate meaning',
    'description' => '',
    'parent_id' => '2170',
    'children' => true,
  ),
  2182 => 
  array (
    'short_name' => '',
    'standard_id' => '2182',
    'name' => 'Ideas synthesized from informational texts serve a specific purpose',
    'description' => '',
    'parent_id' => '2170',
    'children' => true,
  ),
  8015 => 
  array (
    'short_name' => '',
    'standard_id' => '8015',
    'name' => 'Knowledge of language, including syntax and grammar, influence the understanding of literary, persuasive, and informational texts',
    'description' => '',
    'parent_id' => '2170',
    'children' => true,
  ),
  2210 => 
  array (
    'short_name' => '',
    'standard_id' => '2210',
    'name' => '10',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2212 => 
  array (
    'short_name' => '',
    'standard_id' => '2212',
    'name' => 'Literary and historical influences determine the meaning of traditional and contemporary literary texts',
    'description' => '',
    'parent_id' => '2210',
    'children' => true,
  ),
  2227 => 
  array (
    'short_name' => '',
    'standard_id' => '2227',
    'name' => 'The development of new ideas and concepts within informational and persuasive manuscripts',
    'description' => '',
    'parent_id' => '2210',
    'children' => true,
  ),
  8071 => 
  array (
    'short_name' => '',
    'standard_id' => '8071',
    'name' => 'Context, parts of speech, grammar, and word choice influence the understanding of literary, persuasive, and informational texts',
    'description' => '',
    'parent_id' => '2210',
    'children' => true,
  ),
  2251 => 
  array (
    'short_name' => '',
    'standard_id' => '2251',
    'name' => '9',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2254 => 
  array (
    'short_name' => '',
    'standard_id' => '2254',
    'name' => 'Increasingly complex literary elements in traditional and contemporary works of literature require scrutiny and comparison',
    'description' => '',
    'parent_id' => '2251',
    'children' => true,
  ),
  2265 => 
  array (
    'short_name' => '',
    'standard_id' => '2265',
    'name' => 'Increasingly complex informational texts require mature interpretation and study',
    'description' => '',
    'parent_id' => '2251',
    'children' => true,
  ),
  2277 => 
  array (
    'short_name' => '',
    'standard_id' => '2277',
    'name' => '8',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2279 => 
  array (
    'short_name' => '',
    'standard_id' => '2279',
    'name' => 'Quality comprehension and interpretation of literary texts demand self-monitoring and self-assessment',
    'description' => '',
    'parent_id' => '2277',
    'children' => true,
  ),
  2293 => 
  array (
    'short_name' => '',
    'standard_id' => '2293',
    'name' => 'Quality comprehension and interpretation of informational and persuasive texts demand monitoring and self-assessment',
    'description' => '',
    'parent_id' => '2277',
    'children' => true,
  ),
  2323 => 
  array (
    'short_name' => '',
    'standard_id' => '2323',
    'name' => 'Context, grammar, and word choice influence the understanding of literary, persuasive, and informational texts',
    'description' => '',
    'parent_id' => '2277',
    'children' => true,
  ),
  2352 => 
  array (
    'short_name' => '',
    'standard_id' => '2352',
    'name' => '7',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2360 => 
  array (
    'short_name' => '',
    'standard_id' => '2360',
    'name' => 'Literary elements, characteristics, and ideas are interrelated and guide the comprehension of literary and fictional texts',
    'description' => '',
    'parent_id' => '2352',
    'children' => true,
  ),
  2381 => 
  array (
    'short_name' => '',
    'standard_id' => '2381',
    'name' => 'Informational and persuasive texts are summarized and evaluated',
    'description' => '',
    'parent_id' => '2352',
    'children' => true,
  ),
  2390 => 
  array (
    'short_name' => '',
    'standard_id' => '2390',
    'name' => 'Purpose, tone, and meaning in word choices influence literary, persuasive, and informational texts',
    'description' => '',
    'parent_id' => '2352',
    'children' => true,
  ),
  2399 => 
  array (
    'short_name' => '',
    'standard_id' => '2399',
    'name' => '6',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2400 => 
  array (
    'short_name' => '',
    'standard_id' => '2400',
    'name' => 'Understanding the meaning within different types of literature depends on properly analyzing literary components',
    'description' => '',
    'parent_id' => '2399',
    'children' => true,
  ),
  2408 => 
  array (
    'short_name' => '',
    'standard_id' => '2408',
    'name' => 'Organizing structure to understand and analyze factual information',
    'description' => '',
    'parent_id' => '2399',
    'children' => true,
  ),
  2450 => 
  array (
    'short_name' => '',
    'standard_id' => '2450',
    'name' => 'Word meanings are determined by how they are designed and how they are used in context',
    'description' => '',
    'parent_id' => '2399',
    'children' => true,
  ),
  2459 => 
  array (
    'short_name' => '',
    'standard_id' => '2459',
    'name' => '5',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2460 => 
  array (
    'short_name' => '',
    'standard_id' => '2460',
    'name' => 'Literary texts are understood and interpreted using a range of strategies',
    'description' => '',
    'parent_id' => '2459',
    'children' => true,
  ),
  2470 => 
  array (
    'short_name' => '',
    'standard_id' => '2470',
    'name' => 'Ideas found in a variety of informational texts need to be compared and understood',
    'description' => '',
    'parent_id' => '2459',
    'children' => true,
  ),
  2482 => 
  array (
    'short_name' => '',
    'standard_id' => '2482',
    'name' => 'Knowledge of morphology and word relationships matters when reading',
    'description' => '',
    'parent_id' => '2459',
    'children' => true,
  ),
  2493 => 
  array (
    'short_name' => '',
    'standard_id' => '2493',
    'name' => '4',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2494 => 
  array (
    'short_name' => '',
    'standard_id' => '2494',
    'name' => 'Comprehension and fluency matter when reading literary texts in a facile way',
    'description' => '',
    'parent_id' => '2493',
    'children' => true,
  ),
  2500 => 
  array (
    'short_name' => '',
    'standard_id' => '2500',
    'name' => 'Comprehension and fluency matter when reading informational and persuasive texts in a facile way',
    'description' => '',
    'parent_id' => '2493',
    'children' => true,
  ),
  2509 => 
  array (
    'short_name' => '',
    'standard_id' => '2509',
    'name' => 'Knowledge of complex orthography (spelling patterns), morphology (word meanings), and word relationships to decode (read) multisyllabic words contributes to better reading skills',
    'description' => 'Knowledge of complex orthography (spelling patterns), morphology (word meanings), and word relationships to decode (read) multisyllabic words contributes to better reading skills',
    'parent_id' => '2493',
    'children' => true,
  ),
  2515 => 
  array (
    'short_name' => '',
    'standard_id' => '2515',
    'name' => '3',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2516 => 
  array (
    'short_name' => '',
    'standard_id' => '2516',
    'name' => 'Strategies are needed to make meaning of various types of literary genres',
    'description' => '',
    'parent_id' => '2515',
    'children' => true,
  ),
  2523 => 
  array (
    'short_name' => '',
    'standard_id' => '2523',
    'name' => 'Comprehension strategies are necessary when reading informational or persuasive text',
    'description' => '',
    'parent_id' => '2515',
    'children' => true,
  ),
  2533 => 
  array (
    'short_name' => '',
    'standard_id' => '2533',
    'name' => 'Increasing word understanding, word use, and word relationships increases vocabulary',
    'description' => '',
    'parent_id' => '2515',
    'children' => true,
  ),
  2540 => 
  array (
    'short_name' => '',
    'standard_id' => '2540',
    'name' => '2',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2544 => 
  array (
    'short_name' => '',
    'standard_id' => '2544',
    'name' => 'Fluent reading depends on specific skills and approaches to understanding strategies when reading literary text',
    'description' => '',
    'parent_id' => '2540',
    'children' => true,
  ),
  2553 => 
  array (
    'short_name' => '',
    'standard_id' => '2553',
    'name' => 'Fluent reading depends on specific skills and approaches to understanding strategies when reading informational text',
    'description' => '',
    'parent_id' => '2540',
    'children' => true,
  ),
  2564 => 
  array (
    'short_name' => '',
    'standard_id' => '2564',
    'name' => 'Decoding words with accuracy depends on knowledge of complex spelling patterns and morphology',
    'description' => '',
    'parent_id' => '2540',
    'children' => true,
  ),
  2574 => 
  array (
    'short_name' => '',
    'standard_id' => '2574',
    'name' => '1',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2575 => 
  array (
    'short_name' => '',
    'standard_id' => '2575',
    'name' => 'Comprehending and fluently reading a variety of literary and informational texts are the beginning traits of readers',
    'description' => '',
    'parent_id' => '2574',
    'children' => true,
  ),
  2589 => 
  array (
    'short_name' => '',
    'standard_id' => '2589',
    'name' => 'Decoding words require the application of alphabetic principles, letter sounds, and letter combinations',
    'description' => '',
    'parent_id' => '2574',
    'children' => true,
  ),
  2602 => 
  array (
    'short_name' => '',
    'standard_id' => '2602',
    'name' => 'Understanding word structure, word relationships, and word families needs to be demonstrated to begin to read',
    'description' => '',
    'parent_id' => '2574',
    'children' => true,
  ),
  8479 => 
  array (
    'short_name' => '',
    'standard_id' => '8479',
    'name' => 'Comprehending and fluently reading a variety of informational texts are the beginning traits of readers',
    'description' => '',
    'parent_id' => '2574',
    'children' => true,
  ),
  2620 => 
  array (
    'short_name' => '',
    'standard_id' => '2620',
    'name' => 'K',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2621 => 
  array (
    'short_name' => '',
    'standard_id' => '2621',
    'name' => 'A concept of print to read and a solid comprehension of literary informational text are the building blocks for reading',
    'description' => '',
    'parent_id' => '2620',
    'children' => true,
  ),
  2632 => 
  array (
    'short_name' => '',
    'standard_id' => '2632',
    'name' => 'Decoding words in print requires alphabet recognition and knowledge of letter sounds',
    'description' => '',
    'parent_id' => '2620',
    'children' => true,
  ),
  8533 => 
  array (
    'short_name' => '',
    'standard_id' => '8533',
    'name' => 'A concept of print to read and a solid comprehension of informational text are the building blocks for reading',
    'description' => '',
    'parent_id' => '2620',
    'children' => true,
  ),
  2658 => 
  array (
    'short_name' => '',
    'standard_id' => '2658',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '2146',
    'children' => true,
  ),
  2659 => 
  array (
    'short_name' => '',
    'standard_id' => '2659',
    'name' => 'Print conveys meaning',
    'description' => '',
    'parent_id' => '2658',
    'children' => true,
  ),
  2672 => 
  array (
    'short_name' => '',
    'standard_id' => '2672',
    'name' => 'Symbol, object, and letter recognition is a fundamental of reading and requires accuracy and speed',
    'description' => '',
    'parent_id' => '2658',
    'children' => true,
  ),
  2686 => 
  array (
    'short_name' => '',
    'standard_id' => '2686',
    'name' => 'Standard: 3. Writing and Composition',
    'description' => '',
    'parent_id' => '1633',
    'children' => true,
  ),
  2690 => 
  array (
    'short_name' => '',
    'standard_id' => '2690',
    'name' => '12',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  2693 => 
  array (
    'short_name' => '',
    'standard_id' => '2693',
    'name' => 'Style, detail, expressive language, and genre create a well-crafted statement directed at an intended audience and purpose',
    'description' => '',
    'parent_id' => '2690',
    'children' => true,
  ),
  2712 => 
  array (
    'short_name' => '',
    'standard_id' => '2712',
    'name' => 'Ideas, evidence, structure, and style create persuasive, academic, and technical texts for particular audiences and specific purposes',
    'description' => '',
    'parent_id' => '2690',
    'children' => true,
  ),
  2734 => 
  array (
    'short_name' => '',
    'standard_id' => '2734',
    'name' => 'Standard English conventions effectively communicate to targeted audiences and purposes',
    'description' => '',
    'parent_id' => '2690',
    'children' => true,
  ),
  2751 => 
  array (
    'short_name' => '',
    'standard_id' => '2751',
    'name' => '11',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  2777 => 
  array (
    'short_name' => '',
    'standard_id' => '2777',
    'name' => 'Stylistic and thematic elements of literary or narrative texts can be refined to engage or entertain an audience',
    'description' => '',
    'parent_id' => '2751',
    'children' => true,
  ),
  2804 => 
  array (
    'short_name' => '',
    'standard_id' => '2804',
    'name' => 'Elements of informational and persuasive texts can be refined to inform or influence an audience',
    'description' => '',
    'parent_id' => '2751',
    'children' => true,
  ),
  2821 => 
  array (
    'short_name' => '',
    'standard_id' => '2821',
    'name' => 'Writing demands ongoing revisions and refinements for grammar, usage, mechanics, and clarity',
    'description' => 'Writing demands ongoing revisions and refinements for grammar, usage, mechanics, and clarity',
    'parent_id' => '2751',
    'children' => true,
  ),
  2753 => 
  array (
    'short_name' => '',
    'standard_id' => '2753',
    'name' => '10',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  2838 => 
  array (
    'short_name' => '',
    'standard_id' => '2838',
    'name' => 'Literary or narrative genres feature a variety of stylistic devices to engage or entertain an audience',
    'description' => '',
    'parent_id' => '2753',
    'children' => true,
  ),
  2859 => 
  array (
    'short_name' => '',
    'standard_id' => '2859',
    'name' => 'Organizational writing patterns inform or persuade an audience',
    'description' => '',
    'parent_id' => '2753',
    'children' => true,
  ),
  2898 => 
  array (
    'short_name' => '',
    'standard_id' => '2898',
    'name' => 'Grammar, language usage, mechanics, and clarity are the basis of ongoing refinements and revisions within the writing process',
    'description' => '',
    'parent_id' => '2753',
    'children' => true,
  ),
  2754 => 
  array (
    'short_name' => '',
    'standard_id' => '2754',
    'name' => '9',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  2933 => 
  array (
    'short_name' => '',
    'standard_id' => '2933',
    'name' => 'Literary and narrative texts develop a controlling idea or theme with descriptive and expressive language',
    'description' => '',
    'parent_id' => '2754',
    'children' => true,
  ),
  2955 => 
  array (
    'short_name' => '',
    'standard_id' => '2955',
    'name' => 'Informational and persuasive texts develop a topic and establish a controlling idea or thesis with relevant support',
    'description' => '',
    'parent_id' => '2754',
    'children' => true,
  ),
  2984 => 
  array (
    'short_name' => '',
    'standard_id' => '2984',
    'name' => 'Writing for grammar, usage, mechanics, and clarity requires ongoing refinements and revisions',
    'description' => '',
    'parent_id' => '2754',
    'children' => true,
  ),
  2755 => 
  array (
    'short_name' => '',
    'standard_id' => '2755',
    'name' => '8',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  2996 => 
  array (
    'short_name' => '',
    'standard_id' => '2996',
    'name' => 'Stylistic devices and descriptive details in literary and narrative texts are organized for a variety of audiences and purposes and evaluated for quality',
    'description' => '',
    'parent_id' => '2755',
    'children' => true,
  ),
  3010 => 
  array (
    'short_name' => '',
    'standard_id' => '3010',
    'name' => 'Ideas and supporting details in informational and persuasive texts are organized for a variety of audiences and purposes and evaluated for quality',
    'description' => '',
    'parent_id' => '2755',
    'children' => true,
  ),
  3022 => 
  array (
    'short_name' => '',
    'standard_id' => '3022',
    'name' => 'Editing writing for grammar, usage, mechanics, and clarity is an essential trait of a well-written document',
    'description' => '',
    'parent_id' => '2755',
    'children' => true,
  ),
  2757 => 
  array (
    'short_name' => '',
    'standard_id' => '2757',
    'name' => '7',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3045 => 
  array (
    'short_name' => '',
    'standard_id' => '3045',
    'name' => 'Composing literary and narrative texts that incorporate a range of stylistic devices demonstrates knowledge of genre features',
    'description' => '',
    'parent_id' => '2757',
    'children' => true,
  ),
  3071 => 
  array (
    'short_name' => '',
    'standard_id' => '3071',
    'name' => 'Organization is used when composing informational and persuasive texts',
    'description' => '',
    'parent_id' => '2757',
    'children' => true,
  ),
  3087 => 
  array (
    'short_name' => '',
    'standard_id' => '3087',
    'name' => 'Editing writing for proper grammar, usage, mechanics, and clarity improves written work',
    'description' => '',
    'parent_id' => '2757',
    'children' => true,
  ),
  2759 => 
  array (
    'short_name' => '',
    'standard_id' => '2759',
    'name' => '6',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3118 => 
  array (
    'short_name' => '',
    'standard_id' => '3118',
    'name' => 'Writing literary genres for intended audiences and purposes requires ideas, organization, and voice',
    'description' => '',
    'parent_id' => '2759',
    'children' => true,
  ),
  3132 => 
  array (
    'short_name' => '',
    'standard_id' => '3132',
    'name' => 'Writing informational and persuasive genres for intended audiences and purposes require ideas, organization, and voice develop',
    'description' => '',
    'parent_id' => '2759',
    'children' => true,
  ),
  3163 => 
  array (
    'short_name' => '',
    'standard_id' => '3163',
    'name' => 'Specific editing for grammar, usage, mechanics, and clarity gives writing its precision and legitimacy',
    'description' => '',
    'parent_id' => '2759',
    'children' => true,
  ),
  2760 => 
  array (
    'short_name' => '',
    'standard_id' => '2760',
    'name' => '5',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3337 => 
  array (
    'short_name' => '',
    'standard_id' => '3337',
    'name' => 'The recursive writing process contributes to the creative and unique literary genres for a variety of audiences and purposes',
    'description' => '',
    'parent_id' => '2760',
    'children' => true,
  ),
  3343 => 
  array (
    'short_name' => '',
    'standard_id' => '3343',
    'name' => 'The recursive writing process creates stronger informational and persuasive texts for a variety of audiences and purposes',
    'description' => '',
    'parent_id' => '2760',
    'children' => true,
  ),
  3351 => 
  array (
    'short_name' => '',
    'standard_id' => '3351',
    'name' => 'Conventions apply consistently when evaluating written texts',
    'description' => '',
    'parent_id' => '2760',
    'children' => true,
  ),
  2762 => 
  array (
    'short_name' => '',
    'standard_id' => '2762',
    'name' => '4',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3358 => 
  array (
    'short_name' => '',
    'standard_id' => '3358',
    'name' => 'The recursive writing process is used to create a variety of literary genres for an intended audience',
    'description' => '',
    'parent_id' => '2762',
    'children' => true,
  ),
  3365 => 
  array (
    'short_name' => '',
    'standard_id' => '3365',
    'name' => 'Informational and persuasive texts use the recursive writing process',
    'description' => '',
    'parent_id' => '2762',
    'children' => true,
  ),
  3384 => 
  array (
    'short_name' => '',
    'standard_id' => '3384',
    'name' => 'Correct sentence formation, grammar, punctuation, capitalization, and spelling are applied to make the meaning clear to the reader',
    'description' => '',
    'parent_id' => '2762',
    'children' => true,
  ),
  2764 => 
  array (
    'short_name' => '',
    'standard_id' => '2764',
    'name' => '3',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3410 => 
  array (
    'short_name' => '',
    'standard_id' => '3410',
    'name' => 'A writing process is used to plan, draft, and write a variety of literary genres',
    'description' => '',
    'parent_id' => '2764',
    'children' => true,
  ),
  3421 => 
  array (
    'short_name' => '',
    'standard_id' => '3421',
    'name' => 'A writing process is used to plan, draft, and write a variety of informational texts',
    'description' => '',
    'parent_id' => '2764',
    'children' => true,
  ),
  3437 => 
  array (
    'short_name' => '',
    'standard_id' => '3437',
    'name' => 'Correct grammar, capitalization, punctuation, and spelling are used when writing',
    'description' => '',
    'parent_id' => '2764',
    'children' => true,
  ),
  2765 => 
  array (
    'short_name' => '',
    'standard_id' => '2765',
    'name' => '2',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3449 => 
  array (
    'short_name' => '',
    'standard_id' => '3449',
    'name' => 'Exploring the writing process helps to plan and draft a variety of literary genres',
    'description' => '',
    'parent_id' => '2765',
    'children' => true,
  ),
  3457 => 
  array (
    'short_name' => '',
    'standard_id' => '3457',
    'name' => 'Exploring the writing process helps to plan and draft a variety of simple informational texts',
    'description' => '',
    'parent_id' => '2765',
    'children' => true,
  ),
  3465 => 
  array (
    'short_name' => '',
    'standard_id' => '3465',
    'name' => 'Appropriate spelling, capitalization, grammar, and punctuation are used and applied when writing',
    'description' => '',
    'parent_id' => '2765',
    'children' => true,
  ),
  2767 => 
  array (
    'short_name' => '',
    'standard_id' => '2767',
    'name' => '1',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3475 => 
  array (
    'short_name' => '',
    'standard_id' => '3475',
    'name' => 'Exploring the writing process develops ideas for writing texts that carry meaning',
    'description' => '',
    'parent_id' => '2767',
    'children' => true,
  ),
  3481 => 
  array (
    'short_name' => '',
    'standard_id' => '3481',
    'name' => 'Appropriate spelling, conventions, and grammar are applied when writing',
    'description' => '',
    'parent_id' => '2767',
    'children' => true,
  ),
  2769 => 
  array (
    'short_name' => '',
    'standard_id' => '2769',
    'name' => 'K',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3495 => 
  array (
    'short_name' => '',
    'standard_id' => '3495',
    'name' => 'Appropriate mechanics and conventions are used to create simple texts',
    'description' => '',
    'parent_id' => '2769',
    'children' => true,
  ),
  9051 => 
  array (
    'short_name' => '',
    'standard_id' => '9051',
    'name' => 'Text types and purposes, labels, and familiar words are used to communicate information and ideas',
    'description' => '',
    'parent_id' => '2769',
    'children' => true,
  ),
  2770 => 
  array (
    'short_name' => '',
    'standard_id' => '2770',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '2686',
    'children' => true,
  ),
  3504 => 
  array (
    'short_name' => '',
    'standard_id' => '3504',
    'name' => 'Pictures express ideas',
    'description' => '',
    'parent_id' => '2770',
    'children' => true,
  ),
  3510 => 
  array (
    'short_name' => '',
    'standard_id' => '3510',
    'name' => 'Letters are formed with accuracy',
    'description' => '',
    'parent_id' => '2770',
    'children' => true,
  ),
  3514 => 
  array (
    'short_name' => '',
    'standard_id' => '3514',
    'name' => 'Standard: 4. Research and Reasoning',
    'description' => '',
    'parent_id' => '1633',
    'children' => true,
  ),
  3515 => 
  array (
    'short_name' => '',
    'standard_id' => '3515',
    'name' => '12',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3529 => 
  array (
    'short_name' => '',
    'standard_id' => '3529',
    'name' => 'Independent research designs articulate and defend information, conclusions and solutions that address specific contexts and purposes',
    'description' => '',
    'parent_id' => '3515',
    'children' => true,
  ),
  3537 => 
  array (
    'short_name' => '',
    'standard_id' => '3537',
    'name' => 'Logical arguments distinguish facts from opinions, and evidence defines reasoned judgment',
    'description' => '',
    'parent_id' => '3515',
    'children' => true,
  ),
  3516 => 
  array (
    'short_name' => '',
    'standard_id' => '3516',
    'name' => '11',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3544 => 
  array (
    'short_name' => '',
    'standard_id' => '3544',
    'name' => 'Self-designed research provides insightful information, conclusions, and possible solutions',
    'description' => '',
    'parent_id' => '3516',
    'children' => true,
  ),
  3552 => 
  array (
    'short_name' => '',
    'standard_id' => '3552',
    'name' => 'Complex situations require critical thinking across multiple disciplines',
    'description' => '',
    'parent_id' => '3516',
    'children' => true,
  ),
  3559 => 
  array (
    'short_name' => '',
    'standard_id' => '3559',
    'name' => 'Evaluating quality reasoning includes the value of intellectual character such as humility, empathy, and confidence',
    'description' => '',
    'parent_id' => '3516',
    'children' => true,
  ),
  3517 => 
  array (
    'short_name' => '',
    'standard_id' => '3517',
    'name' => '10',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3565 => 
  array (
    'short_name' => '',
    'standard_id' => '3565',
    'name' => 'Collect, analyze, and evaluate information obtained from multiple sources to answer a question, propose solutions, or share findings and conclusions',
    'description' => '',
    'parent_id' => '3517',
    'children' => true,
  ),
  3573 => 
  array (
    'short_name' => '',
    'standard_id' => '3573',
    'name' => 'An author\'s reasoning is the essence of legitimate writing and requires evaluating text for validity and accuracy',
    'description' => '',
    'parent_id' => '3517',
    'children' => true,
  ),
  3518 => 
  array (
    'short_name' => '',
    'standard_id' => '3518',
    'name' => '9',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3577 => 
  array (
    'short_name' => '',
    'standard_id' => '3577',
    'name' => 'Informational materials, including electronic sources, need to be collected, evaluated, and analyzed for accuracy, relevance, and effectiveness for answering research questions',
    'description' => '',
    'parent_id' => '3518',
    'children' => true,
  ),
  3583 => 
  array (
    'short_name' => '',
    'standard_id' => '3583',
    'name' => 'Effective problem-solving strategies require high-quality reasoning',
    'description' => '',
    'parent_id' => '3518',
    'children' => true,
  ),
  3519 => 
  array (
    'short_name' => '',
    'standard_id' => '3519',
    'name' => '8',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3589 => 
  array (
    'short_name' => '',
    'standard_id' => '3589',
    'name' => 'Individual research projects begin with information obtained from a variety of sources, and is organized, documented, and presented using logical procedures',
    'description' => '',
    'parent_id' => '3519',
    'children' => true,
  ),
  3597 => 
  array (
    'short_name' => '',
    'standard_id' => '3597',
    'name' => 'Common fallacies and errors occur in reasoning',
    'description' => '',
    'parent_id' => '3519',
    'children' => true,
  ),
  3603 => 
  array (
    'short_name' => '',
    'standard_id' => '3603',
    'name' => 'Quality reasoning relies on supporting evidence in media',
    'description' => '',
    'parent_id' => '3519',
    'children' => true,
  ),
  3520 => 
  array (
    'short_name' => '',
    'standard_id' => '3520',
    'name' => '7',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3609 => 
  array (
    'short_name' => '',
    'standard_id' => '3609',
    'name' => 'Answering a research question logically begins with obtaining and analyzing information from a variety of sources',
    'description' => '',
    'parent_id' => '3520',
    'children' => true,
  ),
  3616 => 
  array (
    'short_name' => '',
    'standard_id' => '3616',
    'name' => 'Logical information requires documented sources',
    'description' => '',
    'parent_id' => '3520',
    'children' => true,
  ),
  3621 => 
  array (
    'short_name' => '',
    'standard_id' => '3621',
    'name' => 'Reasoned material is evaluated for its quality using both its logic and its use of a medium',
    'description' => '',
    'parent_id' => '3520',
    'children' => true,
  ),
  3521 => 
  array (
    'short_name' => '',
    'standard_id' => '3521',
    'name' => '6',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3627 => 
  array (
    'short_name' => '',
    'standard_id' => '3627',
    'name' => 'Individual and group research projects require obtaining information on a topic from a variety of sources and organizing it for presentation',
    'description' => '',
    'parent_id' => '3521',
    'children' => true,
  ),
  3634 => 
  array (
    'short_name' => '',
    'standard_id' => '3634',
    'name' => 'Assumptions can be concealed, and require identification and evaluation',
    'description' => '',
    'parent_id' => '3521',
    'children' => true,
  ),
  3641 => 
  array (
    'short_name' => '',
    'standard_id' => '3641',
    'name' => 'Monitoring the thinking of self and others is a disciplined way to maintain awareness',
    'description' => '',
    'parent_id' => '3521',
    'children' => true,
  ),
  3522 => 
  array (
    'short_name' => '',
    'standard_id' => '3522',
    'name' => '5',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3645 => 
  array (
    'short_name' => '',
    'standard_id' => '3645',
    'name' => 'High-quality research requires information that is organized and presented with documentation',
    'description' => '',
    'parent_id' => '3522',
    'children' => true,
  ),
  3652 => 
  array (
    'short_name' => '',
    'standard_id' => '3652',
    'name' => 'Identifying and evaluating concepts and ideas have implications and consequences',
    'description' => '',
    'parent_id' => '3522',
    'children' => true,
  ),
  3660 => 
  array (
    'short_name' => '',
    'standard_id' => '3660',
    'name' => 'Quality reasoning requires asking questions and analyzing and evaluating viewpoints',
    'description' => '',
    'parent_id' => '3522',
    'children' => true,
  ),
  3523 => 
  array (
    'short_name' => '',
    'standard_id' => '3523',
    'name' => '4',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3666 => 
  array (
    'short_name' => '',
    'standard_id' => '3666',
    'name' => 'Comprehending new information for research is a process undertaken with discipline both alone and within groups',
    'description' => '',
    'parent_id' => '3523',
    'children' => true,
  ),
  3676 => 
  array (
    'short_name' => '',
    'standard_id' => '3676',
    'name' => 'Identifying implications, concepts, and ideas enriches reasoning skills',
    'description' => '',
    'parent_id' => '3523',
    'children' => true,
  ),
  3524 => 
  array (
    'short_name' => '',
    'standard_id' => '3524',
    'name' => '3',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3682 => 
  array (
    'short_name' => '',
    'standard_id' => '3682',
    'name' => 'Researching a topic and sharing findings are often done with others',
    'description' => '',
    'parent_id' => '3524',
    'children' => true,
  ),
  3687 => 
  array (
    'short_name' => '',
    'standard_id' => '3687',
    'name' => 'Inferences and points of view exist',
    'description' => '',
    'parent_id' => '3524',
    'children' => true,
  ),
  3525 => 
  array (
    'short_name' => '',
    'standard_id' => '3525',
    'name' => '2',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3695 => 
  array (
    'short_name' => '',
    'standard_id' => '3695',
    'name' => 'Reference materials help us locate information and answer questions',
    'description' => '',
    'parent_id' => '3525',
    'children' => true,
  ),
  3701 => 
  array (
    'short_name' => '',
    'standard_id' => '3701',
    'name' => 'Questions are essential to analyze and evaluate the quality of thinking',
    'description' => 'Questions are essential to analyze and evaluate the quality of thinking',
    'parent_id' => '3525',
    'children' => true,
  ),
  3526 => 
  array (
    'short_name' => '',
    'standard_id' => '3526',
    'name' => '1',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3705 => 
  array (
    'short_name' => '',
    'standard_id' => '3705',
    'name' => 'A variety of resources leads to locating information and answering questions of interest',
    'description' => '',
    'parent_id' => '3526',
    'children' => true,
  ),
  3710 => 
  array (
    'short_name' => '',
    'standard_id' => '3710',
    'name' => 'Purpose, information, and questions about an issue are essential steps in early research',
    'description' => '',
    'parent_id' => '3526',
    'children' => true,
  ),
  3527 => 
  array (
    'short_name' => '',
    'standard_id' => '3527',
    'name' => 'K',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3715 => 
  array (
    'short_name' => '',
    'standard_id' => '3715',
    'name' => 'A variety of locations must be explored to find information that answers questions of interest',
    'description' => '',
    'parent_id' => '3527',
    'children' => true,
  ),
  3719 => 
  array (
    'short_name' => '',
    'standard_id' => '3719',
    'name' => 'Identify purpose, information and question at issue',
    'description' => '',
    'parent_id' => '3527',
    'children' => true,
  ),
  3724 => 
  array (
    'short_name' => '',
    'standard_id' => '3724',
    'name' => 'Quality of thinking depends on the quality of questions',
    'description' => 'Quality of thinking depends on the quality of questions',
    'parent_id' => '3527',
    'children' => true,
  ),
  3528 => 
  array (
    'short_name' => '',
    'standard_id' => '3528',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '3514',
    'children' => true,
  ),
  3728 => 
  array (
    'short_name' => '',
    'standard_id' => '3728',
    'name' => 'Relevant information is different from non-relevant information',
    'description' => '',
    'parent_id' => '3528',
    'children' => true,
  ),
  3733 => 
  array (
    'short_name' => '',
    'standard_id' => '3733',
    'name' => 'Problems can be identified and possible solutions can be created',
    'description' => 'Problems can be identified and possible solutions can be created',
    'parent_id' => '3528',
    'children' => true,
  ),
  2240 => 
  array (
    'short_name' => '',
    'standard_id' => '2240',
    'name' => 'Social Studies',
    'description' => '',
    'parent_id' => '775',
    'children' => true,
  ),
  2241 => 
  array (
    'short_name' => '',
    'standard_id' => '2241',
    'name' => 'Standard: 1. History',
    'description' => 'Standard: 1. History',
    'parent_id' => '2240',
    'children' => true,
  ),
  2304 => 
  array (
    'short_name' => '',
    'standard_id' => '2304',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2415 => 
  array (
    'short_name' => '',
    'standard_id' => '2415',
    'name' => 'Use the historical method of inquiry to ask questions, evaluate primary and secondary sources, critically analyze and interpret data, and develop interpretations defended by evidence',
    'description' => 'Use the historical method of inquiry to ask questions, evaluate primary and secondary sources, critically analyze and interpret data, and develop interpretations defended by evidence',
    'parent_id' => '2304',
    'children' => true,
  ),
  2422 => 
  array (
    'short_name' => '',
    'standard_id' => '2422',
    'name' => 'The key concepts of continuity and change, cause and effect, complexity, unity and diversity over time',
    'description' => 'The key concepts of continuity and change, cause and effect, complexity, unity and diversity over time',
    'parent_id' => '2304',
    'children' => true,
  ),
  2442 => 
  array (
    'short_name' => '',
    'standard_id' => '2442',
    'name' => 'The significance of ideas as powerful forces throughout history',
    'description' => 'The significance of ideas as powerful forces throughout history',
    'parent_id' => '2304',
    'children' => true,
  ),
  2306 => 
  array (
    'short_name' => '',
    'standard_id' => '2306',
    'name' => '8',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2599 => 
  array (
    'short_name' => '',
    'standard_id' => '2599',
    'name' => 'Formulate appropriate hypotheses about United States history based on a variety of historical sources and perspectives',
    'description' => 'Formulate appropriate hypotheses about United States history based on a variety of historical sources and perspectives',
    'parent_id' => '2306',
    'children' => true,
  ),
  2608 => 
  array (
    'short_name' => '',
    'standard_id' => '2608',
    'name' => 'The historical eras, individuals, groups, ideas and themes from the origins of the American Revolution through Reconstruction and their relationships with one another',
    'description' => 'The historical eras, individuals, groups, ideas and themes from the origins of the American Revolution through Reconstruction and their relationships with one another',
    'parent_id' => '2306',
    'children' => true,
  ),
  2307 => 
  array (
    'short_name' => '',
    'standard_id' => '2307',
    'name' => '7',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2631 => 
  array (
    'short_name' => '',
    'standard_id' => '2631',
    'name' => 'Seek and evaluate multiple historical sources with different points of view to investigate a historical question and to formulate and defend a thesis with evidence',
    'description' => 'Seek and evaluate multiple historical sources with different points of view to investigate a historical question and to formulate and defend a thesis with evidence',
    'parent_id' => '2307',
    'children' => true,
  ),
  2638 => 
  array (
    'short_name' => '',
    'standard_id' => '2638',
    'name' => 'The historical eras, individuals, groups, ideas and themes within regions of the Eastern Hemisphere and their relationships with one another',
    'description' => 'The historical eras, individuals, groups, ideas and themes within regions of the Eastern Hemisphere and their relationships with one another',
    'parent_id' => '2307',
    'children' => true,
  ),
  2308 => 
  array (
    'short_name' => '',
    'standard_id' => '2308',
    'name' => '6',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2650 => 
  array (
    'short_name' => '',
    'standard_id' => '2650',
    'name' => 'Analyze and interpret historical sources to ask and research historical questions',
    'description' => 'Analyze and interpret historical sources to ask and research historical questions',
    'parent_id' => '2308',
    'children' => true,
  ),
  2660 => 
  array (
    'short_name' => '',
    'standard_id' => '2660',
    'name' => 'The historical eras, individuals, groups, ideas and themes in regions of the Western Hemisphere and their relationships with one another',
    'description' => 'The historical eras, individuals, groups, ideas and themes in regions of the Western Hemisphere and their relationships with one another',
    'parent_id' => '2308',
    'children' => true,
  ),
  2310 => 
  array (
    'short_name' => '',
    'standard_id' => '2310',
    'name' => '5',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2677 => 
  array (
    'short_name' => '',
    'standard_id' => '2677',
    'name' => 'Analyze historical sources from multiple points of view to develop an understanding of historical context',
    'description' => 'Analyze historical sources from multiple points of view to develop an understanding of historical context',
    'parent_id' => '2310',
    'children' => true,
  ),
  2684 => 
  array (
    'short_name' => '',
    'standard_id' => '2684',
    'name' => 'The historical eras, individuals, groups, ideas, and themes in North America from 1491 through the founding of the United States government',
    'description' => 'The historical eras, individuals, groups, ideas, and themes in North America from 1491 through the founding of the United States government',
    'parent_id' => '2310',
    'children' => true,
  ),
  2312 => 
  array (
    'short_name' => '',
    'standard_id' => '2312',
    'name' => '4',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2701 => 
  array (
    'short_name' => '',
    'standard_id' => '2701',
    'name' => 'Organize and sequence events to understand the concepts of chronology and cause and effect in the history of Colorado',
    'description' => 'Organize and sequence events to understand the concepts of chronology and cause and effect in the history of Colorado',
    'parent_id' => '2312',
    'children' => true,
  ),
  2714 => 
  array (
    'short_name' => '',
    'standard_id' => '2714',
    'name' => 'The historical eras, individuals, groups, ideas and themes in Colorado history and their relationships to key events in the United States',
    'description' => 'The historical eras, individuals, groups, ideas and themes in Colorado history and their relationships to key events in the United States',
    'parent_id' => '2312',
    'children' => true,
  ),
  2313 => 
  array (
    'short_name' => '',
    'standard_id' => '2313',
    'name' => '3',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2725 => 
  array (
    'short_name' => '',
    'standard_id' => '2725',
    'name' => 'Use a variety of sources to distinguish historical fact from fiction',
    'description' => 'Use a variety of sources to distinguish historical fact from fiction',
    'parent_id' => '2313',
    'children' => true,
  ),
  2735 => 
  array (
    'short_name' => '',
    'standard_id' => '2735',
    'name' => 'People in the past influence the development and interaction of different communities or regions',
    'description' => 'People in the past influence the development and interaction of different communities or regions',
    'parent_id' => '2313',
    'children' => true,
  ),
  2314 => 
  array (
    'short_name' => '',
    'standard_id' => '2314',
    'name' => '2',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2745 => 
  array (
    'short_name' => '',
    'standard_id' => '2745',
    'name' => 'Identify historical sources and utilize the tools of a historian',
    'description' => 'Identify historical sources and utilize the tools of a historian',
    'parent_id' => '2314',
    'children' => true,
  ),
  2756 => 
  array (
    'short_name' => '',
    'standard_id' => '2756',
    'name' => 'People have influenced the history of neighborhoods and communities',
    'description' => 'People have influenced the history of neighborhoods and communities',
    'parent_id' => '2314',
    'children' => true,
  ),
  2315 => 
  array (
    'short_name' => '',
    'standard_id' => '2315',
    'name' => '1',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2772 => 
  array (
    'short_name' => '',
    'standard_id' => '2772',
    'name' => 'Describe patterns and chronological order of events of the recent past',
    'description' => 'Describe patterns and chronological order of events of the recent past',
    'parent_id' => '2315',
    'children' => true,
  ),
  2784 => 
  array (
    'short_name' => '',
    'standard_id' => '2784',
    'name' => 'Family and cultural traditions in the United States in the past',
    'description' => 'Family and cultural traditions in the United States in the past',
    'parent_id' => '2315',
    'children' => true,
  ),
  2318 => 
  array (
    'short_name' => '',
    'standard_id' => '2318',
    'name' => 'K',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2801 => 
  array (
    'short_name' => '',
    'standard_id' => '2801',
    'name' => 'Ask questions, share information and discuss ideas about the past',
    'description' => 'Ask questions, share information and discuss ideas about the past',
    'parent_id' => '2318',
    'children' => true,
  ),
  2812 => 
  array (
    'short_name' => '',
    'standard_id' => '2812',
    'name' => 'The first component in the concept of chronology is to place information in sequential order',
    'description' => 'The first component in the concept of chronology is to place information in sequential order',
    'parent_id' => '2318',
    'children' => true,
  ),
  2319 => 
  array (
    'short_name' => '',
    'standard_id' => '2319',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '2241',
    'children' => true,
  ),
  2820 => 
  array (
    'short_name' => '',
    'standard_id' => '2820',
    'name' => 'Change and sequence over time',
    'description' => 'Change and sequence over time',
    'parent_id' => '2319',
    'children' => true,
  ),
  2242 => 
  array (
    'short_name' => '',
    'standard_id' => '2242',
    'name' => 'Standard: 2. Geography',
    'description' => 'Standard: 2. Geography',
    'parent_id' => '2240',
    'children' => true,
  ),
  2320 => 
  array (
    'short_name' => '',
    'standard_id' => '2320',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  2834 => 
  array (
    'short_name' => '',
    'standard_id' => '2834',
    'name' => 'Use different types of maps and geographic tools to analyze features on Earth to investigate and solve geographic questions',
    'description' => 'Use different types of maps and geographic tools to analyze features on Earth to investigate and solve geographic questions',
    'parent_id' => '2320',
    'children' => true,
  ),
  2843 => 
  array (
    'short_name' => '',
    'standard_id' => '2843',
    'name' => 'Explain and interpret geographic variables that influence the interactions of people, places and environments',
    'description' => 'Explain and interpret geographic variables that influence the interactions of people, places and environments',
    'parent_id' => '2320',
    'children' => true,
  ),
  2851 => 
  array (
    'short_name' => '',
    'standard_id' => '2851',
    'name' => 'The interconnected nature of the world, its people and places',
    'description' => 'The interconnected nature of the world, its people and places',
    'parent_id' => '2320',
    'children' => true,
  ),
  2321 => 
  array (
    'short_name' => '',
    'standard_id' => '2321',
    'name' => '8',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  2879 => 
  array (
    'short_name' => '',
    'standard_id' => '2879',
    'name' => 'Use geographic tools to analyze patterns in human and physical systems',
    'description' => 'Use geographic tools to analyze patterns in human and physical systems',
    'parent_id' => '2321',
    'children' => true,
  ),
  2887 => 
  array (
    'short_name' => '',
    'standard_id' => '2887',
    'name' => 'Conflict and cooperation occur over space and resources',
    'description' => 'Conflict and cooperation occur over space and resources',
    'parent_id' => '2321',
    'children' => true,
  ),
  2322 => 
  array (
    'short_name' => '',
    'standard_id' => '2322',
    'name' => '7',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  2899 => 
  array (
    'short_name' => '',
    'standard_id' => '2899',
    'name' => 'Use geographic tools to gather data and make geographic inferences and predictions',
    'description' => 'Use geographic tools to gather data and make geographic inferences and predictions',
    'parent_id' => '2322',
    'children' => true,
  ),
  2911 => 
  array (
    'short_name' => '',
    'standard_id' => '2911',
    'name' => 'Regions have different issues and perspectives',
    'description' => 'Regions have different issues and perspectives',
    'parent_id' => '2322',
    'children' => true,
  ),
  2324 => 
  array (
    'short_name' => '',
    'standard_id' => '2324',
    'name' => '6',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  2920 => 
  array (
    'short_name' => '',
    'standard_id' => '2920',
    'name' => 'Use geographic tools to solve problems',
    'description' => 'Use geographic tools to solve problems',
    'parent_id' => '2324',
    'children' => true,
  ),
  2931 => 
  array (
    'short_name' => '',
    'standard_id' => '2931',
    'name' => 'Human and physical systems vary and interact',
    'description' => 'Human and physical systems vary and interact',
    'parent_id' => '2324',
    'children' => true,
  ),
  2325 => 
  array (
    'short_name' => '',
    'standard_id' => '2325',
    'name' => '5',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  2957 => 
  array (
    'short_name' => '',
    'standard_id' => '2957',
    'name' => 'Use various geographic tools and sources to answer questions about the geography of the United States',
    'description' => 'Use various geographic tools and sources to answer questions about the geography of the United States',
    'parent_id' => '2325',
    'children' => true,
  ),
  2972 => 
  array (
    'short_name' => '',
    'standard_id' => '2972',
    'name' => 'Causes and consequences of movement',
    'description' => 'Causes and consequences of movement',
    'parent_id' => '2325',
    'children' => true,
  ),
  2326 => 
  array (
    'short_name' => '',
    'standard_id' => '2326',
    'name' => '4',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  2987 => 
  array (
    'short_name' => '',
    'standard_id' => '2987',
    'name' => 'Use several types of geographic tools to answer questions about the geography of Colorado',
    'description' => 'Use several types of geographic tools to answer questions about the geography of Colorado',
    'parent_id' => '2326',
    'children' => true,
  ),
  2999 => 
  array (
    'short_name' => '',
    'standard_id' => '2999',
    'name' => 'Connections within and across human and physical systems are developed',
    'description' => 'Connections within and across human and physical systems are developed',
    'parent_id' => '2326',
    'children' => true,
  ),
  2328 => 
  array (
    'short_name' => '',
    'standard_id' => '2328',
    'name' => '3',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  3020 => 
  array (
    'short_name' => '',
    'standard_id' => '3020',
    'name' => 'Use various types of geographic tools to develop spatial thinking',
    'description' => 'Use various types of geographic tools to develop spatial thinking',
    'parent_id' => '2328',
    'children' => true,
  ),
  3030 => 
  array (
    'short_name' => '',
    'standard_id' => '3030',
    'name' => 'The concept of regions is developed through an understanding of similarities and differences in places',
    'description' => 'The concept of regions is developed through an understanding of similarities and differences in places',
    'parent_id' => '2328',
    'children' => true,
  ),
  2330 => 
  array (
    'short_name' => '',
    'standard_id' => '2330',
    'name' => '2',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  3040 => 
  array (
    'short_name' => '',
    'standard_id' => '3040',
    'name' => 'Geographic terms and tools are used to describe space and place',
    'description' => 'Geographic terms and tools are used to describe space and place',
    'parent_id' => '2330',
    'children' => true,
  ),
  3047 => 
  array (
    'short_name' => '',
    'standard_id' => '3047',
    'name' => 'People in communities manage, modify and depend on their environment',
    'description' => 'People in communities manage, modify and depend on their environment',
    'parent_id' => '2330',
    'children' => true,
  ),
  2331 => 
  array (
    'short_name' => '',
    'standard_id' => '2331',
    'name' => '1',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  3056 => 
  array (
    'short_name' => '',
    'standard_id' => '3056',
    'name' => 'Geographic tools such as maps and globes represent places',
    'description' => 'Geographic tools such as maps and globes represent places',
    'parent_id' => '2331',
    'children' => true,
  ),
  3068 => 
  array (
    'short_name' => '',
    'standard_id' => '3068',
    'name' => 'People in different groups and communities interact with each other and with the environment',
    'description' => 'People in different groups and communities interact with each other and with the environment',
    'parent_id' => '2331',
    'children' => true,
  ),
  2332 => 
  array (
    'short_name' => '',
    'standard_id' => '2332',
    'name' => 'K',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  3079 => 
  array (
    'short_name' => '',
    'standard_id' => '3079',
    'name' => 'People belong to different groups and live in different places around the world that can be found on a map or globe',
    'description' => 'People belong to different groups and live in different places around the world that can be found on a map or globe',
    'parent_id' => '2332',
    'children' => true,
  ),
  2333 => 
  array (
    'short_name' => '',
    'standard_id' => '2333',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '2242',
    'children' => true,
  ),
  3088 => 
  array (
    'short_name' => '',
    'standard_id' => '3088',
    'name' => 'Develop spatial understanding, perspectives, and connections to the world',
    'description' => 'Develop spatial understanding, perspectives, and connections to the world',
    'parent_id' => '2333',
    'children' => true,
  ),
  2243 => 
  array (
    'short_name' => '',
    'standard_id' => '2243',
    'name' => 'Standard: 3. Economics',
    'description' => 'Standard: 3. Economics',
    'parent_id' => '2240',
    'children' => true,
  ),
  2335 => 
  array (
    'short_name' => '',
    'standard_id' => '2335',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3100 => 
  array (
    'short_name' => '',
    'standard_id' => '3100',
    'name' => 'Productive resources – natural, human, capital – are scarce; therefore, choices are made about how individuals, businesses, governments, and societies allocate these resources',
    'description' => 'Productive resources – natural, human, capital – are scarce; therefore, choices are made about how individuals, businesses, governments, and societies allocate these resources',
    'parent_id' => '2335',
    'children' => true,
  ),
  3110 => 
  array (
    'short_name' => '',
    'standard_id' => '3110',
    'name' => 'Economic policies affect markets',
    'description' => 'Economic policies affect markets',
    'parent_id' => '2335',
    'children' => true,
  ),
  3120 => 
  array (
    'short_name' => '',
    'standard_id' => '3120',
    'name' => 'Government and competition affect markets',
    'description' => 'Government and competition affect markets',
    'parent_id' => '2335',
    'children' => true,
  ),
  3134 => 
  array (
    'short_name' => '',
    'standard_id' => '3134',
    'name' => 'Design, analyze, and apply a financial plan based on short- and long-term financial goals (PFL)',
    'description' => 'Design, analyze, and apply a financial plan based on short- and long-term financial goals (PFL)',
    'parent_id' => '2335',
    'children' => true,
  ),
  3150 => 
  array (
    'short_name' => '',
    'standard_id' => '3150',
    'name' => 'Analyze strategic spending, saving, and investment options to achieve the objectives of diversification, liquidity, income, and growth (PFL)',
    'description' => 'Analyze strategic spending, saving, and investment options to achieve the objectives of diversification, liquidity, income, and growth (PFL)',
    'parent_id' => '2335',
    'children' => true,
  ),
  3160 => 
  array (
    'short_name' => '',
    'standard_id' => '3160',
    'name' => 'The components of personal credit to manage credit and debt (PFL)',
    'description' => 'The components of personal credit to manage credit and debt (PFL)',
    'parent_id' => '2335',
    'children' => true,
  ),
  3167 => 
  array (
    'short_name' => '',
    'standard_id' => '3167',
    'name' => 'Identify, develop, and evaluate risk-management strategies (PFL)',
    'description' => 'Identify, develop, and evaluate risk-management strategies (PFL)',
    'parent_id' => '2335',
    'children' => true,
  ),
  2337 => 
  array (
    'short_name' => '',
    'standard_id' => '2337',
    'name' => '8',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3187 => 
  array (
    'short_name' => '',
    'standard_id' => '3187',
    'name' => 'Economic freedom, including free trade, is important for economic growth',
    'description' => 'Economic freedom, including free trade, is important for economic growth',
    'parent_id' => '2337',
    'children' => true,
  ),
  3193 => 
  array (
    'short_name' => '',
    'standard_id' => '3193',
    'name' => 'Manage personal credit and debt (PFL)',
    'description' => 'Manage personal credit and debt (PFL)',
    'parent_id' => '2337',
    'children' => true,
  ),
  2338 => 
  array (
    'short_name' => '',
    'standard_id' => '2338',
    'name' => '7',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3203 => 
  array (
    'short_name' => '',
    'standard_id' => '3203',
    'name' => 'Supply and demand influence price and profit in a market economy',
    'description' => 'Supply and demand influence price and profit in a market economy',
    'parent_id' => '2338',
    'children' => true,
  ),
  3216 => 
  array (
    'short_name' => '',
    'standard_id' => '3216',
    'name' => 'The distribution of resources influences economic production and individual choices (Economics and PFL)',
    'description' => 'The distribution of resources influences economic production and individual choices (Economics and PFL)',
    'parent_id' => '2338',
    'children' => true,
  ),
  2339 => 
  array (
    'short_name' => '',
    'standard_id' => '2339',
    'name' => '6',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3228 => 
  array (
    'short_name' => '',
    'standard_id' => '3228',
    'name' => 'Identify and analyze different economic systems',
    'description' => 'Identify and analyze different economic systems',
    'parent_id' => '2339',
    'children' => true,
  ),
  3234 => 
  array (
    'short_name' => '',
    'standard_id' => '3234',
    'name' => 'Saving and investing are key contributors to financial well-being (PFL)',
    'description' => 'Saving and investing are key contributors to financial well-being (PFL)',
    'parent_id' => '2339',
    'children' => true,
  ),
  2340 => 
  array (
    'short_name' => '',
    'standard_id' => '2340',
    'name' => '5',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3243 => 
  array (
    'short_name' => '',
    'standard_id' => '3243',
    'name' => 'Government and market structures influence financial institutions',
    'description' => 'Government and market structures influence financial institutions',
    'parent_id' => '2340',
    'children' => true,
  ),
  3249 => 
  array (
    'short_name' => '',
    'standard_id' => '3249',
    'name' => 'Use of financial institutions to manage personal finances (PFL)',
    'description' => 'Use of financial institutions to manage personal finances (PFL)',
    'parent_id' => '2340',
    'children' => true,
  ),
  2342 => 
  array (
    'short_name' => '',
    'standard_id' => '2342',
    'name' => '4',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3255 => 
  array (
    'short_name' => '',
    'standard_id' => '3255',
    'name' => 'People respond to positive and negative incentives',
    'description' => 'People respond to positive and negative incentives',
    'parent_id' => '2342',
    'children' => true,
  ),
  3261 => 
  array (
    'short_name' => '',
    'standard_id' => '3261',
    'name' => 'The relationship between choice and opportunity cost (PFL)',
    'description' => 'The relationship between choice and opportunity cost (PFL)',
    'parent_id' => '2342',
    'children' => true,
  ),
  2343 => 
  array (
    'short_name' => '',
    'standard_id' => '2343',
    'name' => '3',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3271 => 
  array (
    'short_name' => '',
    'standard_id' => '3271',
    'name' => 'Describe producers and consumers and how goods and services are exchanged',
    'description' => 'Describe producers and consumers and how goods and services are exchanged',
    'parent_id' => '2343',
    'children' => true,
  ),
  3282 => 
  array (
    'short_name' => '',
    'standard_id' => '3282',
    'name' => 'Describe how to meet short term financial goals (PFL)',
    'description' => '',
    'parent_id' => '2343',
    'children' => true,
  ),
  2344 => 
  array (
    'short_name' => '',
    'standard_id' => '2344',
    'name' => '2',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3292 => 
  array (
    'short_name' => '',
    'standard_id' => '3292',
    'name' => 'The scarcity of resources affects the choices of individuals and communities',
    'description' => 'The scarcity of resources affects the choices of individuals and communities',
    'parent_id' => '2344',
    'children' => true,
  ),
  3298 => 
  array (
    'short_name' => '',
    'standard_id' => '3298',
    'name' => 'Apply decision-making processes to financial decisions (PFL)',
    'description' => 'Apply decision-making processes to financial decisions (PFL)',
    'parent_id' => '2344',
    'children' => true,
  ),
  2346 => 
  array (
    'short_name' => '',
    'standard_id' => '2346',
    'name' => '1',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3302 => 
  array (
    'short_name' => '',
    'standard_id' => '3302',
    'name' => 'People work at different types of jobs and in different types of organizations to produce goods and services and receive an income',
    'description' => 'People work at different types of jobs and in different types of organizations to produce goods and services and receive an income',
    'parent_id' => '2346',
    'children' => true,
  ),
  3307 => 
  array (
    'short_name' => '',
    'standard_id' => '3307',
    'name' => 'Identify short-term financial goals (PFL)',
    'description' => 'Identify short-term financial goals (PFL)',
    'parent_id' => '2346',
    'children' => true,
  ),
  2347 => 
  array (
    'short_name' => '',
    'standard_id' => '2347',
    'name' => 'K',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3314 => 
  array (
    'short_name' => '',
    'standard_id' => '3314',
    'name' => 'Ownership as a component of economics',
    'description' => 'Ownership as a component of economics',
    'parent_id' => '2347',
    'children' => true,
  ),
  3319 => 
  array (
    'short_name' => '',
    'standard_id' => '3319',
    'name' => 'Discuss how purchases can be made to meet wants and needs (PFL)',
    'description' => 'Discuss how purchases can be made to meet wants and needs (PFL)',
    'parent_id' => '2347',
    'children' => true,
  ),
  2348 => 
  array (
    'short_name' => '',
    'standard_id' => '2348',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '2243',
    'children' => true,
  ),
  3326 => 
  array (
    'short_name' => '',
    'standard_id' => '3326',
    'name' => 'People work to meet wants and needs',
    'description' => 'People work to meet wants and needs',
    'parent_id' => '2348',
    'children' => true,
  ),
  3331 => 
  array (
    'short_name' => '',
    'standard_id' => '3331',
    'name' => 'Recognize money and identify its purpose (PFL)',
    'description' => 'Recognize money and identify its purpose (PFL)',
    'parent_id' => '2348',
    'children' => true,
  ),
  2244 => 
  array (
    'short_name' => '',
    'standard_id' => '2244',
    'name' => 'Standard: 4. Civics',
    'description' => 'Standard: 4. Civics',
    'parent_id' => '2240',
    'children' => true,
  ),
  2349 => 
  array (
    'short_name' => '',
    'standard_id' => '2349',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3738 => 
  array (
    'short_name' => '',
    'standard_id' => '3738',
    'name' => 'Research, formulate positions, and engage in appropriate civic participation to address local, state, and national issues or policies',
    'description' => '',
    'parent_id' => '2349',
    'children' => true,
  ),
  3745 => 
  array (
    'short_name' => '',
    'standard_id' => '3745',
    'name' => 'Purposes of and limitations on the foundations, structures and functions of government',
    'description' => 'Purposes of and limitations on the foundations, structures and functions of government',
    'parent_id' => '2349',
    'children' => true,
  ),
  3754 => 
  array (
    'short_name' => '',
    'standard_id' => '3754',
    'name' => 'Analyze how public policy - domestic and foreign - is developed at the local, state, and national levels and compare how policy-making occurs in other forms of government',
    'description' => 'Analyze how public policy - domestic and foreign - is developed at the local, state, and national levels and compare how policy-making occurs in other forms of government',
    'parent_id' => '2349',
    'children' => true,
  ),
  2350 => 
  array (
    'short_name' => '',
    'standard_id' => '2350',
    'name' => '8',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3762 => 
  array (
    'short_name' => '',
    'standard_id' => '3762',
    'name' => 'Analyze elements of continuity and change in the United States government and the role of citizens over time',
    'description' => 'Analyze elements of continuity and change in the United States government and the role of citizens over time',
    'parent_id' => '2350',
    'children' => true,
  ),
  3770 => 
  array (
    'short_name' => '',
    'standard_id' => '3770',
    'name' => 'The place of law in a constitutional system',
    'description' => 'The place of law in a constitutional system',
    'parent_id' => '2350',
    'children' => true,
  ),
  2351 => 
  array (
    'short_name' => '',
    'standard_id' => '2351',
    'name' => '7',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3779 => 
  array (
    'short_name' => '',
    'standard_id' => '3779',
    'name' => 'Compare how various nations define the rights, responsibilities, and roles of citizens',
    'description' => 'Compare how various nations define the rights, responsibilities, and roles of citizens',
    'parent_id' => '2351',
    'children' => true,
  ),
  3786 => 
  array (
    'short_name' => '',
    'standard_id' => '3786',
    'name' => 'Different forms of government and international organizations and their influence in the world community',
    'description' => 'Different forms of government and international organizations and their influence in the world community',
    'parent_id' => '2351',
    'children' => true,
  ),
  2353 => 
  array (
    'short_name' => '',
    'standard_id' => '2353',
    'name' => '6',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3793 => 
  array (
    'short_name' => '',
    'standard_id' => '3793',
    'name' => 'Analyze the interconnectedness of the United States and other nations',
    'description' => 'Analyze the interconnectedness of the United States and other nations',
    'parent_id' => '2353',
    'children' => true,
  ),
  3801 => 
  array (
    'short_name' => '',
    'standard_id' => '3801',
    'name' => 'Compare multiple systems of government',
    'description' => 'Compare multiple systems of government',
    'parent_id' => '2353',
    'children' => true,
  ),
  2354 => 
  array (
    'short_name' => '',
    'standard_id' => '2354',
    'name' => '5',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3807 => 
  array (
    'short_name' => '',
    'standard_id' => '3807',
    'name' => 'The foundations of citizenship in the United States',
    'description' => 'The foundations of citizenship in the United States',
    'parent_id' => '2354',
    'children' => true,
  ),
  3813 => 
  array (
    'short_name' => '',
    'standard_id' => '3813',
    'name' => 'The origins, structure, and functions of the United States government',
    'description' => 'The origins, structure, and functions of the United States government',
    'parent_id' => '2354',
    'children' => true,
  ),
  2355 => 
  array (
    'short_name' => '',
    'standard_id' => '2355',
    'name' => '4',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3819 => 
  array (
    'short_name' => '',
    'standard_id' => '3819',
    'name' => 'Analyze and debate multiple perspectives on an issue',
    'description' => 'Analyze and debate multiple perspectives on an issue',
    'parent_id' => '2355',
    'children' => true,
  ),
  3824 => 
  array (
    'short_name' => '',
    'standard_id' => '3824',
    'name' => 'The origins, structure, and functions of the Colorado government',
    'description' => 'The origins, structure, and functions of the Colorado government',
    'parent_id' => '2355',
    'children' => true,
  ),
  2356 => 
  array (
    'short_name' => '',
    'standard_id' => '2356',
    'name' => '3',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3831 => 
  array (
    'short_name' => '',
    'standard_id' => '3831',
    'name' => 'Respecting the views and rights of others is a key component of a democratic society',
    'description' => 'Respecting the views and rights of others is a key component of a democratic society',
    'parent_id' => '2356',
    'children' => true,
  ),
  3836 => 
  array (
    'short_name' => '',
    'standard_id' => '3836',
    'name' => 'The origins, structure, and functions of local government',
    'description' => 'The origins, structure, and functions of local government',
    'parent_id' => '2356',
    'children' => true,
  ),
  2357 => 
  array (
    'short_name' => '',
    'standard_id' => '2357',
    'name' => '2',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3841 => 
  array (
    'short_name' => '',
    'standard_id' => '3841',
    'name' => 'Responsible community members advocate for their ideas',
    'description' => 'Responsible community members advocate for their ideas',
    'parent_id' => '2357',
    'children' => true,
  ),
  3848 => 
  array (
    'short_name' => '',
    'standard_id' => '3848',
    'name' => 'People use multiple ways to resolve conflicts or differences',
    'description' => 'People use multiple ways to resolve conflicts or differences',
    'parent_id' => '2357',
    'children' => true,
  ),
  2358 => 
  array (
    'short_name' => '',
    'standard_id' => '2358',
    'name' => '1',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3854 => 
  array (
    'short_name' => '',
    'standard_id' => '3854',
    'name' => 'Effective groups have responsible leaders and team members',
    'description' => 'Effective groups have responsible leaders and team members',
    'parent_id' => '2358',
    'children' => true,
  ),
  3859 => 
  array (
    'short_name' => '',
    'standard_id' => '3859',
    'name' => 'Notable people, places, holidays and patriotic symbols',
    'description' => 'Notable people, places, holidays and patriotic symbols',
    'parent_id' => '2358',
    'children' => true,
  ),
  2359 => 
  array (
    'short_name' => '',
    'standard_id' => '2359',
    'name' => 'K',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3866 => 
  array (
    'short_name' => '',
    'standard_id' => '3866',
    'name' => 'Participate in making decisions using democratic traditions',
    'description' => 'Participate in making decisions using democratic traditions',
    'parent_id' => '2359',
    'children' => true,
  ),
  3873 => 
  array (
    'short_name' => '',
    'standard_id' => '3873',
    'name' => 'Civic participation takes place in multiple groups',
    'description' => 'Civic participation takes place in multiple groups',
    'parent_id' => '2359',
    'children' => true,
  ),
  2361 => 
  array (
    'short_name' => '',
    'standard_id' => '2361',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '2244',
    'children' => true,
  ),
  3878 => 
  array (
    'short_name' => '',
    'standard_id' => '3878',
    'name' => 'Individuals have unique talents and work with others in groups',
    'description' => 'Individuals have unique talents and work with others in groups',
    'parent_id' => '2361',
    'children' => true,
  ),
  3883 => 
  array (
    'short_name' => '',
    'standard_id' => '3883',
    'name' => 'Rules and their purpose in allowing groups to work effectively',
    'description' => 'Rules and their purpose in allowing groups to work effectively',
    'parent_id' => '2361',
    'children' => true,
  ),
  4001 => 
  array (
    'short_name' => '',
    'standard_id' => '4001',
    'name' => 'Math (2010)',
    'description' => '',
    'parent_id' => '775',
    'children' => true,
  ),
  4041 => 
  array (
    'short_name' => '',
    'standard_id' => '4041',
    'name' => 'Standard: 1. Number  Sense,  Properties, and  Operation',
    'description' => '',
    'parent_id' => '4001',
    'children' => true,
  ),
  4046 => 
  array (
    'short_name' => '',
    'standard_id' => '4046',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4099 => 
  array (
    'short_name' => '',
    'standard_id' => '4099',
    'name' => 'The complex number system includes real numbers and imaginary  numbers',
    'description' => 'The complex number system includes real numbers and imaginary numbers',
    'parent_id' => '4046',
    'children' => true,
  ),
  4100 => 
  array (
    'short_name' => '',
    'standard_id' => '4100',
    'name' => 'Quantitative reasoning is used to make sense of quantities and  their relationships in problem situations',
    'description' => 'Quantitative reasoning is used to make sense of quantities and 
their relationships in problem situations',
    'parent_id' => '4046',
    'children' => true,
  ),
  4047 => 
  array (
    'short_name' => '',
    'standard_id' => '4047',
    'name' => '8',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4131 => 
  array (
    'short_name' => '',
    'standard_id' => '4131',
    'name' => 'In the real number system, rational and irrational numbers are in one to one correspondence to points on the number line',
    'description' => 'In the real number system, rational and irrational numbers are in one to one correspondence to points on the number line',
    'parent_id' => '4047',
    'children' => true,
  ),
  4048 => 
  array (
    'short_name' => '',
    'standard_id' => '4048',
    'name' => '7',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4140 => 
  array (
    'short_name' => '',
    'standard_id' => '4140',
    'name' => 'Proportional reasoning involves comparisons and multiplicative relationships among ratios',
    'description' => 'Proportional reasoning involves comparisons and multiplicative relationships among ratios',
    'parent_id' => '4048',
    'children' => true,
  ),
  4142 => 
  array (
    'short_name' => '',
    'standard_id' => '4142',
    'name' => 'Formulate, represent, and use algorithms with rational numbers flexibly, accurately, and efficiently',
    'description' => 'Formulate, represent, and use algorithms with rational numbers flexibly, accurately, and efficiently',
    'parent_id' => '4048',
    'children' => true,
  ),
  4049 => 
  array (
    'short_name' => '',
    'standard_id' => '4049',
    'name' => '6',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4155 => 
  array (
    'short_name' => '',
    'standard_id' => '4155',
    'name' => 'Quantities can be expressed and compared using ratios and rates',
    'description' => 'Quantities can be expressed and compared using ratios and rates',
    'parent_id' => '4049',
    'children' => true,
  ),
  4156 => 
  array (
    'short_name' => '',
    'standard_id' => '4156',
    'name' => 'Formulate, represent, and use algorithms with positive rational numbers with flexibility, accuracy, and efficiency',
    'description' => 'Formulate, represent, and use algorithms with positive rational numbers with flexibility, accuracy, and efficiency',
    'parent_id' => '4049',
    'children' => true,
  ),
  4157 => 
  array (
    'short_name' => '',
    'standard_id' => '4157',
    'name' => 'In the real number system, rational numbers have a unique location on the number line and in space',
    'description' => 'In the real number system, rational numbers have a unique location on the number line and in space',
    'parent_id' => '4049',
    'children' => true,
  ),
  4050 => 
  array (
    'short_name' => '',
    'standard_id' => '4050',
    'name' => '5',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4162 => 
  array (
    'short_name' => '',
    'standard_id' => '4162',
    'name' => 'The decimal number system describes place value patterns and relationships that are repeated in large and small numbers and forms the foundation for efficient algorithms',
    'description' => 'The decimal number system describes place value patterns and relationships that are repeated in large and small numbers and forms the foundation for efficient algorithms',
    'parent_id' => '4050',
    'children' => true,
  ),
  4163 => 
  array (
    'short_name' => '',
    'standard_id' => '4163',
    'name' => 'Formulate, represent, and use algorithms with multi-digit whole numbers and decimals with flexibility, accuracy, and efficiency',
    'description' => 'Formulate, represent, and use algorithms with multi-digit whole numbers and decimals with flexibility, accuracy, and efficiency',
    'parent_id' => '4050',
    'children' => true,
  ),
  4164 => 
  array (
    'short_name' => '',
    'standard_id' => '4164',
    'name' => 'Formulate, represent, and use algorithms to add and subtract fractions with flexibility, accuracy, and efficiency',
    'description' => 'Formulate, represent, and use algorithms to add and subtract fractions with flexibility, accuracy, and efficiency',
    'parent_id' => '4050',
    'children' => true,
  ),
  4165 => 
  array (
    'short_name' => '',
    'standard_id' => '4165',
    'name' => 'The concepts of multiplication and division can be applied to multiply and divide fractions',
    'description' => 'The concepts of multiplication and division can be applied to multiply and divide fractions',
    'parent_id' => '4050',
    'children' => true,
  ),
  4051 => 
  array (
    'short_name' => '',
    'standard_id' => '4051',
    'name' => '4',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4170 => 
  array (
    'short_name' => '',
    'standard_id' => '4170',
    'name' => 'The decimal number system to the hundredths place describes  place value patterns and relationships that are repeated in large  and small numbers and forms the foundation for efficient  algorithms',
    'description' => 'The decimal number system to the hundredths place describes place value patterns and relationships that are repeated in large and small numbers and forms the foundation for efficient algorithms',
    'parent_id' => '4051',
    'children' => true,
  ),
  4171 => 
  array (
    'short_name' => '',
    'standard_id' => '4171',
    'name' => 'Different models and representations can be used to compare fractional parts',
    'description' => 'Different models and representations can be used to compare fractional parts',
    'parent_id' => '4051',
    'children' => true,
  ),
  4172 => 
  array (
    'short_name' => '',
    'standard_id' => '4172',
    'name' => 'Formulate, represent, and use algorithms to compute with flexibility, accuracy, and efficiency',
    'description' => 'Formulate, represent, and use algorithms to compute with flexibility, accuracy, and efficiency',
    'parent_id' => '4051',
    'children' => true,
  ),
  4052 => 
  array (
    'short_name' => '',
    'standard_id' => '4052',
    'name' => '3',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4182 => 
  array (
    'short_name' => '',
    'standard_id' => '4182',
    'name' => 'The whole number system describes place value relationships and forms the foundation for efficient algorithms',
    'description' => 'The whole number system describes place value relationships and forms the foundation for efficient algorithms',
    'parent_id' => '4052',
    'children' => true,
  ),
  4184 => 
  array (
    'short_name' => '',
    'standard_id' => '4184',
    'name' => 'Parts of a whole can be modeled and represented in different ways',
    'description' => 'Parts of a whole can be modeled and represented in different ways',
    'parent_id' => '4052',
    'children' => true,
  ),
  4186 => 
  array (
    'short_name' => '',
    'standard_id' => '4186',
    'name' => 'Multiplication and division are inverse operations and can be modeled in a variety of ways',
    'description' => 'Multiplication and division are inverse operations and can be modeled in a variety of ways',
    'parent_id' => '4052',
    'children' => true,
  ),
  4053 => 
  array (
    'short_name' => '',
    'standard_id' => '4053',
    'name' => '2',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4206 => 
  array (
    'short_name' => '',
    'standard_id' => '4206',
    'name' => 'The whole number system describes place value relationships through 1,000 and forms the foundation for efficient algorithms',
    'description' => 'The whole number system describes place value relationships through 1,000 and forms the foundation for efficient algorithms',
    'parent_id' => '4053',
    'children' => true,
  ),
  4207 => 
  array (
    'short_name' => '',
    'standard_id' => '4207',
    'name' => 'Formulate, represent, and use strategies to add and subtract within 100 with flexibility, accuracy, and efficiency',
    'description' => 'Formulate, represent, and use strategies to add and subtract within 100 with flexibility, accuracy, and efficiency',
    'parent_id' => '4053',
    'children' => true,
  ),
  4054 => 
  array (
    'short_name' => '',
    'standard_id' => '4054',
    'name' => '1',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4213 => 
  array (
    'short_name' => '',
    'standard_id' => '4213',
    'name' => 'The whole number system describes place value relationships within and beyond 100 and forms the foundation for efficient algorithms',
    'description' => 'The whole number system describes place value relationships within and beyond 100 and forms the foundation for efficient algorithms',
    'parent_id' => '4054',
    'children' => true,
  ),
  4216 => 
  array (
    'short_name' => '',
    'standard_id' => '4216',
    'name' => 'Number relationships can be used to solve addition and subtraction problems ',
    'description' => 'Number relationships can be used to solve addition and subtraction problems ',
    'parent_id' => '4054',
    'children' => true,
  ),
  4055 => 
  array (
    'short_name' => '',
    'standard_id' => '4055',
    'name' => 'K',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4228 => 
  array (
    'short_name' => '',
    'standard_id' => '4228',
    'name' => 'Whole numbers can be used to name, count, represent, and order quantity',
    'description' => 'Whole numbers can be used to name, count, represent, and order quantity',
    'parent_id' => '4055',
    'children' => true,
  ),
  4229 => 
  array (
    'short_name' => '',
    'standard_id' => '4229',
    'name' => 'Composing and decomposing quantity forms the foundation for addition and subtraction',
    'description' => 'Composing and decomposing quantity forms the foundation for addition and subtraction',
    'parent_id' => '4055',
    'children' => true,
  ),
  4056 => 
  array (
    'short_name' => '',
    'standard_id' => '4056',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '4041',
    'children' => true,
  ),
  4241 => 
  array (
    'short_name' => '',
    'standard_id' => '4241',
    'name' => 'Quantities can be represented and counted',
    'description' => 'Quantities can be represented and counted',
    'parent_id' => '4056',
    'children' => true,
  ),
  4043 => 
  array (
    'short_name' => '',
    'standard_id' => '4043',
    'name' => 'Standard: 2.  Patterns,  Functions, and  Algebraic  Structure',
    'description' => '',
    'parent_id' => '4001',
    'children' => true,
  ),
  4057 => 
  array (
    'short_name' => '',
    'standard_id' => '4057',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '4043',
    'children' => true,
  ),
  4104 => 
  array (
    'short_name' => '',
    'standard_id' => '4104',
    'name' => 'Functions model situations where one quantity determines another and can be represented algebraically, graphically, and using tables',
    'description' => 'Functions model situations where one quantity determines another and can be represented algebraically, graphically, and using tables',
    'parent_id' => '4057',
    'children' => true,
  ),
  4108 => 
  array (
    'short_name' => '',
    'standard_id' => '4108',
    'name' => 'Quantitative relationships in the real world can be modeled and solved using functions',
    'description' => 'Quantitative relationships in the real world can be modeled and solved using functions',
    'parent_id' => '4057',
    'children' => true,
  ),
  4110 => 
  array (
    'short_name' => '',
    'standard_id' => '4110',
    'name' => 'Expressions can be represented in multiple, equivalent forms',
    'description' => 'Expressions can be represented in multiple, equivalent forms',
    'parent_id' => '4057',
    'children' => true,
  ),
  4111 => 
  array (
    'short_name' => '',
    'standard_id' => '4111',
    'name' => 'Solutions to equations, inequalities and systems of equations are found using a variety of tools',
    'description' => 'Solutions to equations, inequalities and systems of equations are found using a variety of tools',
    'parent_id' => '4057',
    'children' => true,
  ),
  4058 => 
  array (
    'short_name' => '',
    'standard_id' => '4058',
    'name' => '8',
    'description' => '',
    'parent_id' => '4043',
    'children' => true,
  ),
  4132 => 
  array (
    'short_name' => '',
    'standard_id' => '4132',
    'name' => 'Linear functions model situations with a constant rate of change and can be represented numerically, algebraically, and graphically',
    'description' => 'Linear functions model situations with a constant rate of change and can be represented numerically, algebraically, and graphically',
    'parent_id' => '4058',
    'children' => true,
  ),
  4133 => 
  array (
    'short_name' => '',
    'standard_id' => '4133',
    'name' => 'Properties of algebra and equality are used to solve linear equations and systems of equations',
    'description' => 'Properties of algebra and equality are used to solve linear equations and systems of equations',
    'parent_id' => '4058',
    'children' => true,
  ),
  4134 => 
  array (
    'short_name' => '',
    'standard_id' => '4134',
    'name' => 'Graphs, tables and equations can be used to distinguish between linear and nonlinear functions',
    'description' => 'Graphs, tables and equations can be used to distinguish between linear and nonlinear functions',
    'parent_id' => '4058',
    'children' => true,
  ),
  4059 => 
  array (
    'short_name' => '',
    'standard_id' => '4059',
    'name' => '7',
    'description' => '',
    'parent_id' => '4043',
    'children' => true,
  ),
  4146 => 
  array (
    'short_name' => '',
    'standard_id' => '4146',
    'name' => 'Properties of arithmetic can be used to generate equivalent  expressions',
    'description' => 'Properties of arithmetic can be used to generate equivalent expressions',
    'parent_id' => '4059',
    'children' => true,
  ),
  4148 => 
  array (
    'short_name' => '',
    'standard_id' => '4148',
    'name' => 'Equations and expressions model quantitative relationships and  phenomena',
    'description' => 'Equations and expressions model quantitative relationships and phenomena',
    'parent_id' => '4059',
    'children' => true,
  ),
  4060 => 
  array (
    'short_name' => '',
    'standard_id' => '4060',
    'name' => '6',
    'description' => '',
    'parent_id' => '4043',
    'children' => true,
  ),
  4158 => 
  array (
    'short_name' => '',
    'standard_id' => '4158',
    'name' => 'Algebraic expressions can be used to generalize properties of arithmetic ',
    'description' => 'Algebraic expressions can be used to generalize properties of arithmetic ',
    'parent_id' => '4060',
    'children' => true,
  ),
  4159 => 
  array (
    'short_name' => '',
    'standard_id' => '4159',
    'name' => 'Variables are used to represent unknown quantities within equations and inequalities',
    'description' => 'Variables are used to represent unknown quantities within equations and inequalities',
    'parent_id' => '4060',
    'children' => true,
  ),
  4061 => 
  array (
    'short_name' => '',
    'standard_id' => '4061',
    'name' => '5',
    'description' => '',
    'parent_id' => '4043',
    'children' => true,
  ),
  4166 => 
  array (
    'short_name' => '',
    'standard_id' => '4166',
    'name' => 'Number patterns are based on operations and relationships',
    'description' => 'Number patterns are based on operations and relationships',
    'parent_id' => '4061',
    'children' => true,
  ),
  4062 => 
  array (
    'short_name' => '',
    'standard_id' => '4062',
    'name' => '4',
    'description' => '',
    'parent_id' => '4043',
    'children' => true,
  ),
  4173 => 
  array (
    'short_name' => '',
    'standard_id' => '4173',
    'name' => 'Number patterns and relationships can be represented by symbols',
    'description' => 'Number patterns and relationships can be represented by symbols',
    'parent_id' => '4062',
    'children' => true,
  ),
  4044 => 
  array (
    'short_name' => '',
    'standard_id' => '4044',
    'name' => 'Standard: 3.  Data  Analysis,  Statistics, and  Probabilit',
    'description' => '',
    'parent_id' => '4001',
    'children' => true,
  ),
  4068 => 
  array (
    'short_name' => '',
    'standard_id' => '4068',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4112 => 
  array (
    'short_name' => '',
    'standard_id' => '4112',
    'name' => 'Visual displays and summary statistics condense the information in  data sets into usable knowledge ',
    'description' => 'Visual displays and summary statistics condense the information in data sets into usable knowledge ',
    'parent_id' => '4068',
    'children' => true,
  ),
  4113 => 
  array (
    'short_name' => '',
    'standard_id' => '4113',
    'name' => 'Statistical methods take variability into account supporting informed decisions making through quantitative studies designed to answer specific questions',
    'description' => 'Statistical methods take variability into account supporting informed decisions making through quantitative studies designed to answer specific questions',
    'parent_id' => '4068',
    'children' => true,
  ),
  4114 => 
  array (
    'short_name' => '',
    'standard_id' => '4114',
    'name' => 'Probability models outcomes for situations in which there is inherent randomness ',
    'description' => 'Probability models outcomes for situations in which there is inherent randomness ',
    'parent_id' => '4068',
    'children' => true,
  ),
  4069 => 
  array (
    'short_name' => '',
    'standard_id' => '4069',
    'name' => '8',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4135 => 
  array (
    'short_name' => '',
    'standard_id' => '4135',
    'name' => 'Visual displays and summary statistics of two-variable data condense the information in data sets into usable knowledge',
    'description' => 'Visual displays and summary statistics of two-variable data condense the information in data sets into usable knowledge',
    'parent_id' => '4069',
    'children' => true,
  ),
  4070 => 
  array (
    'short_name' => '',
    'standard_id' => '4070',
    'name' => '7',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4151 => 
  array (
    'short_name' => '',
    'standard_id' => '4151',
    'name' => 'Statistics can be used to gain information about populations by  examining samples',
    'description' => 'Statistics can be used to gain information about populations by examining samples',
    'parent_id' => '4070',
    'children' => true,
  ),
  4152 => 
  array (
    'short_name' => '',
    'standard_id' => '4152',
    'name' => 'Mathematical models are used to determine probability',
    'description' => 'Mathematical models are used to determine probability',
    'parent_id' => '4070',
    'children' => true,
  ),
  4071 => 
  array (
    'short_name' => '',
    'standard_id' => '4071',
    'name' => '6',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4160 => 
  array (
    'short_name' => '',
    'standard_id' => '4160',
    'name' => 'Visual displays and summary statistics of one-variable data condense the information in data sets into usable knowledge',
    'description' => 'Visual displays and summary statistics of one-variable data condense the information in data sets into usable knowledge',
    'parent_id' => '4071',
    'children' => true,
  ),
  4072 => 
  array (
    'short_name' => '',
    'standard_id' => '4072',
    'name' => '5',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4167 => 
  array (
    'short_name' => '',
    'standard_id' => '4167',
    'name' => 'Visual displays are used to interpret data',
    'description' => 'Visual displays are used to interpret data',
    'parent_id' => '4072',
    'children' => true,
  ),
  4073 => 
  array (
    'short_name' => '',
    'standard_id' => '4073',
    'name' => '4',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4174 => 
  array (
    'short_name' => '',
    'standard_id' => '4174',
    'name' => 'Visual displays are used to represent data',
    'description' => 'Visual displays are used to represent data',
    'parent_id' => '4073',
    'children' => true,
  ),
  4074 => 
  array (
    'short_name' => '',
    'standard_id' => '4074',
    'name' => '3',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4191 => 
  array (
    'short_name' => '',
    'standard_id' => '4191',
    'name' => 'Visual displays are used to describe data',
    'description' => 'Visual displays are used to describe data',
    'parent_id' => '4074',
    'children' => true,
  ),
  4075 => 
  array (
    'short_name' => '',
    'standard_id' => '4075',
    'name' => '2',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4208 => 
  array (
    'short_name' => '',
    'standard_id' => '4208',
    'name' => 'Visual displays of data can be constructed in a variety of formats to solve problems',
    'description' => 'Visual displays of data can be constructed in a variety of formats to solve problems',
    'parent_id' => '4075',
    'children' => true,
  ),
  4076 => 
  array (
    'short_name' => '',
    'standard_id' => '4076',
    'name' => '1',
    'description' => '',
    'parent_id' => '4044',
    'children' => true,
  ),
  4218 => 
  array (
    'short_name' => '',
    'standard_id' => '4218',
    'name' => 'Visual displays of information can be used to answer questions',
    'description' => 'Visual displays of information can be used to answer questions',
    'parent_id' => '4076',
    'children' => true,
  ),
  4045 => 
  array (
    'short_name' => '',
    'standard_id' => '4045',
    'name' => 'Standard: 4.  Shape,  Dimension, and  Geometric  Relationship',
    'description' => '',
    'parent_id' => '4001',
    'children' => true,
  ),
  4079 => 
  array (
    'short_name' => '',
    'standard_id' => '4079',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4115 => 
  array (
    'short_name' => '',
    'standard_id' => '4115',
    'name' => 'Objects in the plane can be transformed, and those transformations can be described and analyzed mathematically',
    'description' => 'Objects in the plane can be transformed, and those transformations can be described and analyzed mathematically',
    'parent_id' => '4079',
    'children' => true,
  ),
  4116 => 
  array (
    'short_name' => '',
    'standard_id' => '4116',
    'name' => 'Concepts of similarity are foundational to geometry and its applications',
    'description' => 'Concepts of similarity are foundational to geometry and its applications',
    'parent_id' => '4079',
    'children' => true,
  ),
  4117 => 
  array (
    'short_name' => '',
    'standard_id' => '4117',
    'name' => 'Objects in the plane can be described and analyzed algebraically',
    'description' => 'Objects in the plane can be described and analyzed algebraically',
    'parent_id' => '4079',
    'children' => true,
  ),
  4118 => 
  array (
    'short_name' => '',
    'standard_id' => '4118',
    'name' => 'Attributes of two- and three-dimensional objects are measurable and can be quantified',
    'description' => 'Attributes of two- and three-dimensional objects are measurable and can be quantified',
    'parent_id' => '4079',
    'children' => true,
  ),
  4121 => 
  array (
    'short_name' => '',
    'standard_id' => '4121',
    'name' => 'Objects in the real world can be modeled using geometric concepts',
    'description' => 'Objects in the real world can be modeled using geometric concepts',
    'parent_id' => '4079',
    'children' => true,
  ),
  4080 => 
  array (
    'short_name' => '',
    'standard_id' => '4080',
    'name' => '8',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4136 => 
  array (
    'short_name' => '',
    'standard_id' => '4136',
    'name' => 'Transformations of objects can be used to define the concepts of congruence and similarity',
    'description' => 'Transformations of objects can be used to define the concepts of congruence and similarity',
    'parent_id' => '4080',
    'children' => true,
  ),
  4137 => 
  array (
    'short_name' => '',
    'standard_id' => '4137',
    'name' => 'Direct and indirect measurement can be used to describe and make comparisons',
    'description' => 'Direct and indirect measurement can be used to describe and make comparisons',
    'parent_id' => '4080',
    'children' => true,
  ),
  4081 => 
  array (
    'short_name' => '',
    'standard_id' => '4081',
    'name' => '7',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4153 => 
  array (
    'short_name' => '',
    'standard_id' => '4153',
    'name' => 'Modeling geometric figures and relationships leads to informal spatial reasoning and proof',
    'description' => 'Modeling geometric figures and relationships leads to informal spatial reasoning and proof',
    'parent_id' => '4081',
    'children' => true,
  ),
  4154 => 
  array (
    'short_name' => '',
    'standard_id' => '4154',
    'name' => 'Linear measure, angle measure, area, and volume are fundamentally different and require different units of measure',
    'description' => 'Linear measure, angle measure, area, and volume are fundamentally different and require different units of measure',
    'parent_id' => '4081',
    'children' => true,
  ),
  4082 => 
  array (
    'short_name' => '',
    'standard_id' => '4082',
    'name' => '6',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4161 => 
  array (
    'short_name' => '',
    'standard_id' => '4161',
    'name' => 'Objects in space and their parts and attributes can be measured and analyzed',
    'description' => 'Objects in space and their parts and attributes can be measured and analyzed',
    'parent_id' => '4082',
    'children' => true,
  ),
  4083 => 
  array (
    'short_name' => '',
    'standard_id' => '4083',
    'name' => '5',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4168 => 
  array (
    'short_name' => '',
    'standard_id' => '4168',
    'name' => 'Properties of multiplication and addition provide the foundation for volume an attribute of solids',
    'description' => 'Properties of multiplication and addition provide the foundation for volume an attribute of solids',
    'parent_id' => '4083',
    'children' => true,
  ),
  4169 => 
  array (
    'short_name' => '',
    'standard_id' => '4169',
    'name' => 'Geometric figures can be described by their attributes and specific locations in the plane',
    'description' => 'Geometric figures can be described by their attributes and specific locations in the plane',
    'parent_id' => '4083',
    'children' => true,
  ),
  4084 => 
  array (
    'short_name' => '',
    'standard_id' => '4084',
    'name' => '4',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4175 => 
  array (
    'short_name' => '',
    'standard_id' => '4175',
    'name' => 'Appropriate measurement tools, units, and systems are used to measure different attributes of objects and time',
    'description' => 'Appropriate measurement tools, units, and systems are used to measure different attributes of objects and time',
    'parent_id' => '4084',
    'children' => true,
  ),
  4176 => 
  array (
    'short_name' => '',
    'standard_id' => '4176',
    'name' => 'Geometric figures in the plane and in space are described and analyzed by their attributes',
    'description' => 'Geometric figures in the plane and in space are described and analyzed by their attributes',
    'parent_id' => '4084',
    'children' => true,
  ),
  4086 => 
  array (
    'short_name' => '',
    'standard_id' => '4086',
    'name' => '3',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4193 => 
  array (
    'short_name' => '',
    'standard_id' => '4193',
    'name' => 'Geometric figures are described by their attributes',
    'description' => 'Geometric figures are described by their attributes',
    'parent_id' => '4086',
    'children' => true,
  ),
  4195 => 
  array (
    'short_name' => '',
    'standard_id' => '4195',
    'name' => 'Linear and area measurement are fundamentally different and require different units of measure',
    'description' => 'Linear and area measurement are fundamentally different and require different units of measure',
    'parent_id' => '4086',
    'children' => true,
  ),
  4197 => 
  array (
    'short_name' => '',
    'standard_id' => '4197',
    'name' => 'Time and attributes of objects can be measured with appropriate tools',
    'description' => 'Time and attributes of objects can be measured with appropriate tools',
    'parent_id' => '4086',
    'children' => true,
  ),
  4087 => 
  array (
    'short_name' => '',
    'standard_id' => '4087',
    'name' => '2',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4209 => 
  array (
    'short_name' => '',
    'standard_id' => '4209',
    'name' => 'Shapes can be described by their attributes and used to represent part/whole relationships ',
    'description' => 'Shapes can be described by their attributes and used to represent part/whole relationships ',
    'parent_id' => '4087',
    'children' => true,
  ),
  4210 => 
  array (
    'short_name' => '',
    'standard_id' => '4210',
    'name' => 'Some attributes of objects are measurable and can be quantified using different tools',
    'description' => 'Some attributes of objects are measurable and can be quantified using different tools',
    'parent_id' => '4087',
    'children' => true,
  ),
  4088 => 
  array (
    'short_name' => '',
    'standard_id' => '4088',
    'name' => '1',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4223 => 
  array (
    'short_name' => '',
    'standard_id' => '4223',
    'name' => 'Shapes can be described by defining attributes and created by composing and decomposing',
    'description' => 'Shapes can be described by defining attributes and created by composing and decomposing',
    'parent_id' => '4088',
    'children' => true,
  ),
  4225 => 
  array (
    'short_name' => '',
    'standard_id' => '4225',
    'name' => 'Measurement is used to compare and order objects and events',
    'description' => 'Measurement is used to compare and order objects and events',
    'parent_id' => '4088',
    'children' => true,
  ),
  4089 => 
  array (
    'short_name' => '',
    'standard_id' => '4089',
    'name' => 'K',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4231 => 
  array (
    'short_name' => '',
    'standard_id' => '4231',
    'name' => 'Shapes are described by their characteristics and position and created by composing and decomposing',
    'description' => 'Shapes are described by their characteristics and position and created by composing and decomposing',
    'parent_id' => '4089',
    'children' => true,
  ),
  4235 => 
  array (
    'short_name' => '',
    'standard_id' => '4235',
    'name' => 'Measurement is used to compare and order objects',
    'description' => 'Measurement is used to compare and order objects',
    'parent_id' => '4089',
    'children' => true,
  ),
  4091 => 
  array (
    'short_name' => '',
    'standard_id' => '4091',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '4045',
    'children' => true,
  ),
  4242 => 
  array (
    'short_name' => '',
    'standard_id' => '4242',
    'name' => 'Shapes can be observed in the world and described in relation to  one another',
    'description' => 'Shapes can be observed in the world and described in relation to one another',
    'parent_id' => '4091',
    'children' => true,
  ),
  4243 => 
  array (
    'short_name' => '',
    'standard_id' => '4243',
    'name' => 'Measurement is used to compare objects',
    'description' => 'Measurement is used to compare objects',
    'parent_id' => '4091',
    'children' => true,
  ),
  4272 => 
  array (
    'short_name' => '',
    'standard_id' => '4272',
    'name' => 'Comprehensive Health and Physical Education',
    'description' => '',
    'parent_id' => '775',
    'children' => true,
  ),
  4273 => 
  array (
    'short_name' => '',
    'standard_id' => '4273',
    'name' => 'Standard: 1.  Movement Competence and Understanding in Physical Education',
    'description' => '',
    'parent_id' => '4272',
    'children' => true,
  ),
  4274 => 
  array (
    'short_name' => '',
    'standard_id' => '4274',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4275 => 
  array (
    'short_name' => '',
    'standard_id' => '4275',
    'name' => 'Participate at a competent level in a variety of lifelong physical activities',
    'description' => '',
    'parent_id' => '4274',
    'children' => true,
  ),
  4313 => 
  array (
    'short_name' => '',
    'standard_id' => '4313',
    'name' => 'Understand the cognitive impact of movement',
    'description' => '',
    'parent_id' => '4274',
    'children' => true,
  ),
  4329 => 
  array (
    'short_name' => '',
    'standard_id' => '4329',
    'name' => 'Apply rules, principles, problem-solving skills and concepts to traditional and nontraditional movement settings',
    'description' => '',
    'parent_id' => '4274',
    'children' => true,
  ),
  4341 => 
  array (
    'short_name' => '',
    'standard_id' => '4341',
    'name' => '8',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4342 => 
  array (
    'short_name' => '',
    'standard_id' => '4342',
    'name' => 'Demonstrate knowledge of principles and concepts for effective rhythmic motor development',
    'description' => '',
    'parent_id' => '4341',
    'children' => true,
  ),
  4391 => 
  array (
    'short_name' => '',
    'standard_id' => '4391',
    'name' => 'Understand and apply game strategies to physical activities and sports',
    'description' => '',
    'parent_id' => '4341',
    'children' => true,
  ),
  4446 => 
  array (
    'short_name' => '',
    'standard_id' => '4446',
    'name' => '7',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4450 => 
  array (
    'short_name' => '',
    'standard_id' => '4450',
    'name' => 'Combine the critical elements of movement and skills concepts',
    'description' => '',
    'parent_id' => '4446',
    'children' => true,
  ),
  4550 => 
  array (
    'short_name' => '',
    'standard_id' => '4550',
    'name' => '6',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4553 => 
  array (
    'short_name' => '',
    'standard_id' => '4553',
    'name' => 'Demonstrate beginning strategies for a variety of games and sports ',
    'description' => '',
    'parent_id' => '4550',
    'children' => true,
  ),
  4575 => 
  array (
    'short_name' => '',
    'standard_id' => '4575',
    'name' => 'Participate in activities that require problem-solving, cooperation, skill assessment, and teambuilding',
    'description' => '',
    'parent_id' => '4550',
    'children' => true,
  ),
  4589 => 
  array (
    'short_name' => '',
    'standard_id' => '4589',
    'name' => 'Use information from a variety of resources to improve performance',
    'description' => '',
    'parent_id' => '4550',
    'children' => true,
  ),
  4604 => 
  array (
    'short_name' => '',
    'standard_id' => '4604',
    'name' => '5',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4605 => 
  array (
    'short_name' => '',
    'standard_id' => '4605',
    'name' => 'Demonstrate mature form for all basic locomotor, nonlocomotor , manipulative, and rhythmic skills',
    'description' => '',
    'parent_id' => '4604',
    'children' => true,
  ),
  4635 => 
  array (
    'short_name' => '',
    'standard_id' => '4635',
    'name' => 'Demonstrate understanding of how to combine and apply movement concepts and principles to learn and develop motor skills',
    'description' => '',
    'parent_id' => '4604',
    'children' => true,
  ),
  4665 => 
  array (
    'short_name' => '',
    'standard_id' => '4665',
    'name' => '4',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4666 => 
  array (
    'short_name' => '',
    'standard_id' => '4666',
    'name' => 'Identify the major characteristics of mature locomotor, nonlocomotor , manipulative, and rhythmic skills',
    'description' => '',
    'parent_id' => '4665',
    'children' => true,
  ),
  4702 => 
  array (
    'short_name' => '',
    'standard_id' => '4702',
    'name' => 'Provide and receive feedback to and from peers using the major characteristics of mature locomotor and manipulative skills',
    'description' => '',
    'parent_id' => '4665',
    'children' => true,
  ),
  4724 => 
  array (
    'short_name' => '',
    'standard_id' => '4724',
    'name' => '3',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4725 => 
  array (
    'short_name' => '',
    'standard_id' => '4725',
    'name' => 'Demonstrate a variety of motor patterns in simple combinations while participating in activities, games, and sports',
    'description' => '',
    'parent_id' => '4724',
    'children' => true,
  ),
  4754 => 
  array (
    'short_name' => '',
    'standard_id' => '4754',
    'name' => 'Perform movements that engage the brain to facilitate learning ',
    'description' => '',
    'parent_id' => '4724',
    'children' => true,
  ),
  4774 => 
  array (
    'short_name' => '',
    'standard_id' => '4774',
    'name' => '2',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4776 => 
  array (
    'short_name' => '',
    'standard_id' => '4776',
    'name' => 'Demonstrate the elements of movement in combination with a variety of locomotor skills',
    'description' => '',
    'parent_id' => '4774',
    'children' => true,
  ),
  4807 => 
  array (
    'short_name' => '',
    'standard_id' => '4807',
    'name' => 'Demonstrate control and balance in traveling and weight-bearing activities using a variety of body parts and implements',
    'description' => '',
    'parent_id' => '4774',
    'children' => true,
  ),
  4827 => 
  array (
    'short_name' => '',
    'standard_id' => '4827',
    'name' => 'Use feedback to improve performance',
    'description' => '',
    'parent_id' => '4774',
    'children' => true,
  ),
  4844 => 
  array (
    'short_name' => '',
    'standard_id' => '4844',
    'name' => '1',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4845 => 
  array (
    'short_name' => '',
    'standard_id' => '4845',
    'name' => 'Demonstrate basic locomotor and nonlocomotor skills, and rhythmic and cross-lateral movements',
    'description' => '',
    'parent_id' => '4844',
    'children' => true,
  ),
  4879 => 
  array (
    'short_name' => '',
    'standard_id' => '4879',
    'name' => 'Demonstrate fundamental manipulative skills',
    'description' => '',
    'parent_id' => '4844',
    'children' => true,
  ),
  4904 => 
  array (
    'short_name' => '',
    'standard_id' => '4904',
    'name' => 'Establish a beginning movement vocabulary',
    'description' => '',
    'parent_id' => '4844',
    'children' => true,
  ),
  4920 => 
  array (
    'short_name' => '',
    'standard_id' => '4920',
    'name' => 'K',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4921 => 
  array (
    'short_name' => '',
    'standard_id' => '4921',
    'name' => 'Demonstrate body and spatial awareness through movement',
    'description' => '',
    'parent_id' => '4920',
    'children' => true,
  ),
  4941 => 
  array (
    'short_name' => '',
    'standard_id' => '4941',
    'name' => 'Locate the major parts of the body',
    'description' => '',
    'parent_id' => '4920',
    'children' => true,
  ),
  4956 => 
  array (
    'short_name' => '',
    'standard_id' => '4956',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '4273',
    'children' => true,
  ),
  4957 => 
  array (
    'short_name' => '',
    'standard_id' => '4957',
    'name' => 'Travel in a variety of directions using basic locomotor skills, and demonstrate understanding of personal and general space',
    'description' => '',
    'parent_id' => '4956',
    'children' => true,
  ),
  4974 => 
  array (
    'short_name' => '',
    'standard_id' => '4974',
    'name' => 'Demonstrate balance',
    'description' => '',
    'parent_id' => '4956',
    'children' => true,
  ),
  4987 => 
  array (
    'short_name' => '',
    'standard_id' => '4987',
    'name' => 'Standard: 2.  Physical and Personal Wellness in Physical Education',
    'description' => '',
    'parent_id' => '4272',
    'children' => true,
  ),
  4988 => 
  array (
    'short_name' => '',
    'standard_id' => '4988',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  4989 => 
  array (
    'short_name' => '',
    'standard_id' => '4989',
    'name' => 'Establish goals based on fitness assessment data, and develop, implement, achieve, and monitor an individual health and fitness plan',
    'description' => '',
    'parent_id' => '4988',
    'children' => true,
  ),
  5009 => 
  array (
    'short_name' => '',
    'standard_id' => '5009',
    'name' => 'Identify community resources to maintain lifelong physical activity',
    'description' => '',
    'parent_id' => '4988',
    'children' => true,
  ),
  5030 => 
  array (
    'short_name' => '',
    'standard_id' => '5030',
    'name' => 'Participate regularly in health-enhancing and personally rewarding physical activity outside of physical education',
    'description' => '',
    'parent_id' => '4988',
    'children' => true,
  ),
  5053 => 
  array (
    'short_name' => '',
    'standard_id' => '5053',
    'name' => '8',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5062 => 
  array (
    'short_name' => '',
    'standard_id' => '5062',
    'name' => 'Identify the personal, physiological, and fitness benefits of participating in a variety of physical activities',
    'description' => '',
    'parent_id' => '5053',
    'children' => true,
  ),
  5077 => 
  array (
    'short_name' => '',
    'standard_id' => '5077',
    'name' => 'Identify preferences for lifetime physical activity',
    'description' => '',
    'parent_id' => '5053',
    'children' => true,
  ),
  5092 => 
  array (
    'short_name' => '',
    'standard_id' => '5092',
    'name' => 'Determine one\'s responsibility for developing skills, acquiring knowledge, and achieving fitness',
    'description' => '',
    'parent_id' => '5053',
    'children' => true,
  ),
  5054 => 
  array (
    'short_name' => '',
    'standard_id' => '5054',
    'name' => '6',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5113 => 
  array (
    'short_name' => '',
    'standard_id' => '5113',
    'name' => 'Set personal goals for improving health-related fitness',
    'description' => '',
    'parent_id' => '5054',
    'children' => true,
  ),
  5127 => 
  array (
    'short_name' => '',
    'standard_id' => '5127',
    'name' => 'Demonstrate the ability to perform self-paced cardiovascular endurance activities',
    'description' => '',
    'parent_id' => '5054',
    'children' => true,
  ),
  5140 => 
  array (
    'short_name' => '',
    'standard_id' => '5140',
    'name' => 'Identify opportunities in school and in the community for regular participation in physical activity to enhance physical fitness',
    'description' => '',
    'parent_id' => '5054',
    'children' => true,
  ),
  5055 => 
  array (
    'short_name' => '',
    'standard_id' => '5055',
    'name' => '5',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5157 => 
  array (
    'short_name' => '',
    'standard_id' => '5157',
    'name' => 'Understand and apply basic principles of training to improving physical fitness',
    'description' => '',
    'parent_id' => '5055',
    'children' => true,
  ),
  5185 => 
  array (
    'short_name' => '',
    'standard_id' => '5185',
    'name' => 'Demonstrate understanding of skill-related components of fitness and how they affect physical performance',
    'description' => '',
    'parent_id' => '5055',
    'children' => true,
  ),
  5198 => 
  array (
    'short_name' => '',
    'standard_id' => '5198',
    'name' => 'Connect the health-related fitness components to the body systems',
    'description' => '',
    'parent_id' => '5055',
    'children' => true,
  ),
  5056 => 
  array (
    'short_name' => '',
    'standard_id' => '5056',
    'name' => '4',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5214 => 
  array (
    'short_name' => '',
    'standard_id' => '5214',
    'name' => 'Explain how the health-related components of fitness affect performance when participating in physical activity',
    'description' => '',
    'parent_id' => '5056',
    'children' => true,
  ),
  5233 => 
  array (
    'short_name' => '',
    'standard_id' => '5233',
    'name' => 'Recognize the relationship between healthy nutrition and exercise ',
    'description' => '',
    'parent_id' => '5056',
    'children' => true,
  ),
  5245 => 
  array (
    'short_name' => '',
    'standard_id' => '5245',
    'name' => 'Recognize the benefits derived from regular, moderate, and vigorous physical activity',
    'description' => '',
    'parent_id' => '5056',
    'children' => true,
  ),
  5057 => 
  array (
    'short_name' => '',
    'standard_id' => '5057',
    'name' => '3',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5260 => 
  array (
    'short_name' => '',
    'standard_id' => '5260',
    'name' => 'Identify the benefits of sustained physical activity that causes increased heart rate and heavy breathing',
    'description' => '',
    'parent_id' => '5057',
    'children' => true,
  ),
  5286 => 
  array (
    'short_name' => '',
    'standard_id' => '5286',
    'name' => 'Understand that the body is composed of water, muscle, bones, organs, fat, and other tissues',
    'description' => '',
    'parent_id' => '5057',
    'children' => true,
  ),
  5058 => 
  array (
    'short_name' => '',
    'standard_id' => '5058',
    'name' => '2',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5305 => 
  array (
    'short_name' => '',
    'standard_id' => '5305',
    'name' => 'Recognize the importance of making the choice to participate in a wide variety of activities that involve locomotion, nonlocomotion, and manipulation of objects outside of physical education class',
    'description' => 'Recognize the importance of making the choice to participate in a wide variety of activities that involve locomotion, nonlocomotion, and manipulation of objects outside of physical education class',
    'parent_id' => '5058',
    'children' => true,
  ),
  5319 => 
  array (
    'short_name' => '',
    'standard_id' => '5319',
    'name' => 'Identify good brain health habits ',
    'description' => '',
    'parent_id' => '5058',
    'children' => true,
  ),
  5059 => 
  array (
    'short_name' => '',
    'standard_id' => '5059',
    'name' => '1',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5338 => 
  array (
    'short_name' => '',
    'standard_id' => '5338',
    'name' => 'Identify the body’s normal reactions to moderate and vigorous physical activity',
    'description' => '',
    'parent_id' => '5059',
    'children' => true,
  ),
  5060 => 
  array (
    'short_name' => '',
    'standard_id' => '5060',
    'name' => 'K',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5356 => 
  array (
    'short_name' => '',
    'standard_id' => '5356',
    'name' => 'Understand that physical activity increases the heart rate, making the heart stronger',
    'description' => '',
    'parent_id' => '5060',
    'children' => true,
  ),
  5061 => 
  array (
    'short_name' => '',
    'standard_id' => '5061',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '4987',
    'children' => true,
  ),
  5369 => 
  array (
    'short_name' => '',
    'standard_id' => '5369',
    'name' => 'Recognize the positive feelings experienced during and after physical activity',
    'description' => '',
    'parent_id' => '5061',
    'children' => true,
  ),
  5490 => 
  array (
    'short_name' => '',
    'standard_id' => '5490',
    'name' => 'Standard: 3.  Emotional and Social Wellness in Physical Education',
    'description' => '',
    'parent_id' => '4272',
    'children' => true,
  ),
  5491 => 
  array (
    'short_name' => '',
    'standard_id' => '5491',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5505 => 
  array (
    'short_name' => '',
    'standard_id' => '5505',
    'name' => 'Demonstrate respect for individual differences in physical activity settings',
    'description' => '',
    'parent_id' => '5491',
    'children' => true,
  ),
  5540 => 
  array (
    'short_name' => '',
    'standard_id' => '5540',
    'name' => 'Demonstrate collaboration, cooperation, and leadership skills',
    'description' => '',
    'parent_id' => '5491',
    'children' => true,
  ),
  5580 => 
  array (
    'short_name' => '',
    'standard_id' => '5580',
    'name' => 'Demonstrate responsible behavior in group settings',
    'description' => '',
    'parent_id' => '5491',
    'children' => true,
  ),
  5492 => 
  array (
    'short_name' => '',
    'standard_id' => '5492',
    'name' => '7',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5611 => 
  array (
    'short_name' => '',
    'standard_id' => '5611',
    'name' => 'Develop strategies to communicate ideas and feelings',
    'description' => '',
    'parent_id' => '5492',
    'children' => true,
  ),
  5633 => 
  array (
    'short_name' => '',
    'standard_id' => '5633',
    'name' => 'Demonstrate inclusiveness in and out of classroom settings',
    'description' => '',
    'parent_id' => '5492',
    'children' => true,
  ),
  5493 => 
  array (
    'short_name' => '',
    'standard_id' => '5493',
    'name' => '6',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5674 => 
  array (
    'short_name' => '',
    'standard_id' => '5674',
    'name' => 'Recognize diverse skill performance in others and how that diversity affects game, activity, and sport participation',
    'description' => '',
    'parent_id' => '5493',
    'children' => true,
  ),
  5693 => 
  array (
    'short_name' => '',
    'standard_id' => '5693',
    'name' => 'Work cooperatively and productively in a group',
    'description' => '',
    'parent_id' => '5493',
    'children' => true,
  ),
  5494 => 
  array (
    'short_name' => '',
    'standard_id' => '5494',
    'name' => '5',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5735 => 
  array (
    'short_name' => '',
    'standard_id' => '5735',
    'name' => 'Assess and take responsibility for personal behavior and stress management',
    'description' => '',
    'parent_id' => '5494',
    'children' => true,
  ),
  5783 => 
  array (
    'short_name' => '',
    'standard_id' => '5783',
    'name' => 'Choose to participate cooperatively and productively in group and individual physical activities',
    'description' => '',
    'parent_id' => '5494',
    'children' => true,
  ),
  5800 => 
  array (
    'short_name' => '',
    'standard_id' => '5800',
    'name' => 'Identify personal activity interests and abilities',
    'description' => '',
    'parent_id' => '5494',
    'children' => true,
  ),
  5495 => 
  array (
    'short_name' => '',
    'standard_id' => '5495',
    'name' => '3',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5817 => 
  array (
    'short_name' => '',
    'standard_id' => '5817',
    'name' => 'Demonstrate positive social behaviors during class',
    'description' => '',
    'parent_id' => '5495',
    'children' => true,
  ),
  5496 => 
  array (
    'short_name' => '',
    'standard_id' => '5496',
    'name' => '2',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5842 => 
  array (
    'short_name' => '',
    'standard_id' => '5842',
    'name' => 'Demonstrate positive and helpful behavior and words toward other students ',
    'description' => '',
    'parent_id' => '5496',
    'children' => true,
  ),
  5497 => 
  array (
    'short_name' => '',
    'standard_id' => '5497',
    'name' => '1',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5856 => 
  array (
    'short_name' => '',
    'standard_id' => '5856',
    'name' => 'Work independently and with others to complete work',
    'description' => '',
    'parent_id' => '5497',
    'children' => true,
  ),
  5873 => 
  array (
    'short_name' => '',
    'standard_id' => '5873',
    'name' => 'Follow the rules of an activity',
    'description' => '',
    'parent_id' => '5497',
    'children' => true,
  ),
  5498 => 
  array (
    'short_name' => '',
    'standard_id' => '5498',
    'name' => 'K',
    'description' => '',
    'parent_id' => '5490',
    'children' => true,
  ),
  5888 => 
  array (
    'short_name' => '',
    'standard_id' => '5888',
    'name' => 'Demonstrate respect for self, others, and equipment',
    'description' => '',
    'parent_id' => '5498',
    'children' => true,
  ),
  5906 => 
  array (
    'short_name' => '',
    'standard_id' => '5906',
    'name' => 'Demonstrate the ability to follow directions',
    'description' => '',
    'parent_id' => '5498',
    'children' => true,
  ),
  5918 => 
  array (
    'short_name' => '',
    'standard_id' => '5918',
    'name' => 'Standard: 4.  Prevention and Risk Management in Physical Education',
    'description' => '',
    'parent_id' => '4272',
    'children' => true,
  ),
  5919 => 
  array (
    'short_name' => '',
    'standard_id' => '5919',
    'name' => '9-12',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  5927 => 
  array (
    'short_name' => '',
    'standard_id' => '5927',
    'name' => 'Understand the risks and safety factors that may affect participation in physical activity',
    'description' => '',
    'parent_id' => '5919',
    'children' => true,
  ),
  5945 => 
  array (
    'short_name' => '',
    'standard_id' => '5945',
    'name' => 'Demonstrate knowledge of safety and emergency response procedures',
    'description' => '',
    'parent_id' => '5919',
    'children' => true,
  ),
  5920 => 
  array (
    'short_name' => '',
    'standard_id' => '5920',
    'name' => '7',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  5959 => 
  array (
    'short_name' => '',
    'standard_id' => '5959',
    'name' => 'Implement safety procedures in the utilization of space and equipment',
    'description' => '',
    'parent_id' => '5920',
    'children' => true,
  ),
  5921 => 
  array (
    'short_name' => '',
    'standard_id' => '5921',
    'name' => '6',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  5974 => 
  array (
    'short_name' => '',
    'standard_id' => '5974',
    'name' => 'Demonstrate knowledge of safe practices in a physical activity setting',
    'description' => '',
    'parent_id' => '5921',
    'children' => true,
  ),
  5922 => 
  array (
    'short_name' => '',
    'standard_id' => '5922',
    'name' => '5',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  5992 => 
  array (
    'short_name' => '',
    'standard_id' => '5992',
    'name' => 'Understand and utilize safe and appropriate warm-up, pacing, and cool-down techniques for injury prevention and safe participation',
    'description' => '',
    'parent_id' => '5922',
    'children' => true,
  ),
  5923 => 
  array (
    'short_name' => '',
    'standard_id' => '5923',
    'name' => '4',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  6007 => 
  array (
    'short_name' => '',
    'standard_id' => '6007',
    'name' => 'Identify and describe the benefits, risks, and safety factors associated with regular participation in physical activity',
    'description' => '',
    'parent_id' => '5923',
    'children' => true,
  ),
  5924 => 
  array (
    'short_name' => '',
    'standard_id' => '5924',
    'name' => '2',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  6028 => 
  array (
    'short_name' => '',
    'standard_id' => '6028',
    'name' => 'Apply rules, procedures ,and safe practices to create a safe school environment with little or no reinforcement',
    'description' => '',
    'parent_id' => '5924',
    'children' => true,
  ),
  5925 => 
  array (
    'short_name' => '',
    'standard_id' => '5925',
    'name' => '1',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  6043 => 
  array (
    'short_name' => '',
    'standard_id' => '6043',
    'name' => 'Develop movement control for safe participation in games and sports',
    'description' => '',
    'parent_id' => '5925',
    'children' => true,
  ),
  5926 => 
  array (
    'short_name' => '',
    'standard_id' => '5926',
    'name' => 'Pre-K',
    'description' => '',
    'parent_id' => '5918',
    'children' => true,
  ),
  6053 => 
  array (
    'short_name' => '',
    'standard_id' => '6053',
    'name' => 'Apply safe practices, rules, and procedures',
    'description' => '',
    'parent_id' => '5926',
    'children' => true,
  ),
);
}
